from django.urls import path, re_path

from . import views


urlpatterns = [
    # main
    path('', views.home_view, name='home'),
    path('home/', views.home_view, name='home'),
    path('dashboard/', views.dashboard_view, name='dashboard'),
    # calendar
    path('calendar/current/', views.calendar_current_month_view, name='current_month'),
    path('calendar/previous/', views.calendar_previous_month_view, name='previous_month'),
    path('calendar/previous-2/', views.calendar_previous_2_month_view, name='previous_2_month'),
    path('calendar/next/', views.calendar_next_month_view, name='next_month'),
    path('calendar/next-2/', views.calendar_next_2_month_view, name='next_2_month'),
    path('dated-task-list/', views.dated_task_list_view, name='dated_task_list'),
    # sale_file
    path('sale-files/', views.SaleFileListView.as_view(), name='sale_file_list'),
    re_path(r'sale-file/update/(?P<pk>[-\w]+)/(?P<unique_url_id>[-\w]+)/', views.SaleFileUpdateView.as_view(), name='sale_file_update'),
    re_path(r'sale-file/delete/(?P<pk>[-\w]+)/(?P<unique_url_id>[-\w]+)/', views.SaleFileDeleteView.as_view(), name='sale_file_delete'),
    re_path(r'sale-file/delete-request/(?P<pk>[-\w]+)/(?P<unique_url_id>[-\w]+)/', views.SaleFileDeleteRequestView.as_view(), name='sale_file_delete_request'),
    re_path(r'sale-file/recover/(?P<pk>[-\w]+)/(?P<unique_url_id>[-\w]+)/', views.SaleFileRecoverView.as_view(), name='sale_file_recover'),
    re_path(r'sale-file/(?P<pk>[-\w]+)/(?P<unique_url_id>[-\w]+)/', views.SaleFileDetailView.as_view(), name='sale_file_detail'),
    re_path(r'sale-file/create/', views.SaleFileCreateView.as_view(), name='sale_file_create'),
    # rent_file
    path('rent-files/', views.RentFileListView.as_view(), name='rent_file_list'),
    re_path(r'rent-file/update/(?P<pk>[-\w]+)/(?P<unique_url_id>[-\w]+)/', views.RentFileUpdateView.as_view(), name='rent_file_update'),
    re_path(r'rent-file/delete/(?P<pk>[-\w]+)/(?P<unique_url_id>[-\w]+)/', views.RentFileDeleteView.as_view(), name='rent_file_delete'),
    re_path(r'rent-file/delete-request/(?P<pk>[-\w]+)/(?P<unique_url_id>[-\w]+)/', views.RentFileDeleteRequestView.as_view(), name='rent_file_delete_request'),
    re_path(r'rent-file/recover/(?P<pk>[-\w]+)/(?P<unique_url_id>[-\w]+)/', views.RentFileRecoverView.as_view(), name='rent_file_recover'),
    re_path(r'rent-file/(?P<pk>[-\w]+)/(?P<unique_url_id>[-\w]+)/', views.RentFileDetailView.as_view(), name='rent_file_detail'),
    re_path(r'rent-file/create/', views.RentFileCreateView.as_view(), name='rent_file_create'),
    # locations
    path('locations/', views.LocationListView.as_view(), name='location_list'),
    re_path(r'location/province/update/(?P<pk>[-\w]+)/', views.ProvinceUpdateView.as_view(), name='province_update'),
    re_path(r'location/city/update/(?P<pk>[-\w]+)/', views.CityUpdateView.as_view(), name='city_update'),
    re_path(r'location/sub_district/update/(?P<pk>[-\w]+)/', views.SubDistrictUpdateView.as_view(), name='sub_district_update'),
    re_path(r'location/district/update/(?P<pk>[-\w]+)/', views.DistrictUpdateView.as_view(), name='district_update'),
    re_path(r'location/province/delete/(?P<pk>[-\w]+)/', views.ProvinceDeleteView.as_view(), name='province_delete'),
    re_path(r'location/city/delete/(?P<pk>[-\w]+)/', views.CityDeleteView.as_view(), name='city_delete'),
    re_path(r'location/sub_district/delete/(?P<pk>[-\w]+)/', views.SubDistrictDeleteView.as_view(), name='sub_district_delete'),
    re_path(r'location/district/delete/(?P<pk>[-\w]+)/', views.DistrictDeleteView.as_view(), name='district_delete'),
    re_path(r'location/province/create/', views.ProvinceCreateView.as_view(), name='province_create'),
    re_path(r'location/city/create/', views.CityCreateView.as_view(), name='city_create'),
    re_path(r'location/district/create/', views.DistrictCreateView.as_view(), name='district_create'),
    re_path(r'location/sub_district/create/', views.SubDistrictCreateView.as_view(), name='sub_district_create'),
    # persons
    path('persons/', views.PersonListView.as_view(), name='person_list'),
    re_path(r'person/update/(?P<pk>[-\w]+)/', views.PersonUpdateView.as_view(), name='person_update'),
    re_path(r'person/delete/(?P<pk>[-\w]+)/', views.PersonDeleteView.as_view(), name='person_delete'),
    re_path(r'person/delete-request/(?P<pk>[-\w]+)/', views.PersonDeleteRequestView.as_view(), name='person_delete_request'),
    re_path(r'person/recover/(?P<pk>[-\w]+)/', views.PersonRecoverView.as_view(), name='person_recover'),
    re_path(r'person/create/', views.PersonCreateView.as_view(), name='person_create'),
    # buyers
    path('buyers/', views.BuyerListView.as_view(), name='buyer_list'),
    re_path(r'buyer/update/(?P<pk>[-\w]+)/(?P<code>[-\w]+)/', views.BuyerUpdateView.as_view(), name='buyer_update'),
    re_path(r'buyer/delete/(?P<pk>[-\w]+)/(?P<code>[-\w]+)/', views.BuyerDeleteView.as_view(), name='buyer_delete'),
    re_path(r'buyer/delete-request/(?P<pk>[-\w]+)/(?P<code>[-\w]+)/', views.BuyerDeleteRequestView.as_view(), name='buyer_delete_request'),
    re_path(r'buyer/recover/(?P<pk>[-\w]+)/(?P<code>[-\w]+)/', views.BuyerRecoverView.as_view(), name='buyer_recover'),
    re_path(r'buyer/(?P<pk>[-\w]+)/(?P<code>[-\w]+)/', views.BuyerDetailView.as_view(), name='buyer_detail'),
    re_path(r'buyers/create/', views.BuyerCreateView.as_view(), name='buyer_create'),
    # renters
    path('renters/', views.RenterListView.as_view(), name='renter_list'),
    re_path(r'renter/update/(?P<pk>[-\w]+)/(?P<code>[-\w]+)/', views.RenterUpdateView.as_view(), name='renter_update'),
    re_path(r'renter/delete/(?P<pk>[-\w]+)/(?P<code>[-\w]+)/', views.RenterDeleteView.as_view(), name='renter_delete'),
    re_path(r'renter/delete-request/(?P<pk>[-\w]+)/(?P<code>[-\w]+)/', views.RenterDeleteRequestView.as_view(), name='renter_delete_request'),
    re_path(r'renter/recover/(?P<pk>[-\w]+)/(?P<code>[-\w]+)/', views.RenterRecoverView.as_view(), name='renter_recover'),
    re_path(r'renter/(?P<pk>[-\w]+)/(?P<code>[-\w]+)/', views.RenterDetailView.as_view(), name='renter_detail'),
    re_path(r'renters/create/', views.RenterCreateView.as_view(), name='renter_create'),
    # tasks
    path('tasks/for-files/', views.TaskFPListView.as_view(), name='task_fp_list'),
    path('tasks/for-customers/', views.TaskCPListView.as_view(), name='task_cp_list'),
    path('tasks/dual/', views.TaskBTListView.as_view(), name='task_bt_list'),
    path('tasks/boss/under-review/', views.TaskBossURListView.as_view(), name='task_bs_ur_list'),
    path('tasks/boss/open/', views.TaskBossOPListView.as_view(), name='task_bs_op_list'),
    path('tasks/boss/close/', views.TaskBossCLListView.as_view(), name='task_bs_cl_list'),
    re_path(r'task/update/(?P<pk>[-\w]+)/(?P<code>[-\w]+)/', views.TaskUpdateView.as_view(), name='task_update'),
    re_path(r'task/result/(?P<pk>[-\w]+)/(?P<code>[-\w]+)/', views.TaskResultView.as_view(), name='task_result'),
    re_path(r'task/detail/(?P<pk>[-\w]+)/(?P<code>[-\w]+)/', views.TaskDetailView.as_view(), name='task_detail'),
    re_path(r'task/delete/(?P<pk>[-\w]+)/(?P<code>[-\w]+)/', views.TaskDeleteView.as_view(), name='task_delete'),
    re_path(r'task/create/', views.TaskCreateView.as_view(), name='task_create'),
    # services
    path('services/visits/', views.VisitListView.as_view(), name='visit_list'),
    re_path(r'visit/update/(?P<pk>[-\w]+)/(?P<code>[-\w]+)/', views.VisitUpdateView.as_view(), name='visit_update'),
    re_path(r'visit/result/(?P<pk>[-\w]+)/(?P<code>[-\w]+)/', views.VisitResultView.as_view(), name='visit_result'),
    re_path(r'visit/detail/(?P<pk>[-\w]+)/(?P<code>[-\w]+)/', views.VisitDetailView.as_view(), name='visit_detail'),
    re_path(r'visit/delete/(?P<pk>[-\w]+)/(?P<code>[-\w]+)/', views.VisitDeleteView.as_view(), name='visit_delete'),
    re_path(r'visit/create/', views.VisitCreateView.as_view(), name='visit_create'),
    path('services/sessions/', views.SessionListView.as_view(), name='session_list'),
    re_path(r'session/update/(?P<pk>[-\w]+)/(?P<code>[-\w]+)/', views.SessionUpdateView.as_view(), name='session_update'),
    re_path(r'session/result/(?P<pk>[-\w]+)/(?P<code>[-\w]+)/', views.SessionResultView.as_view(), name='session_result'),
    re_path(r'session/detail/(?P<pk>[-\w]+)/(?P<code>[-\w]+)/', views.SessionDetailView.as_view(), name='session_detail'),
    re_path(r'session/delete/(?P<pk>[-\w]+)/(?P<code>[-\w]+)/', views.SessionDeleteView.as_view(), name='session_delete'),
    re_path(r'session/create/', views.SessionCreateView.as_view(), name='session_create'),
    path('services/trades/', views.TradeListView.as_view(), name='trade_list'),
    re_path(r'trade/update/(?P<pk>[-\w]+)/(?P<code>[-\w]+)/', views.TradeUpdateView.as_view(), name='trade_update'),
    re_path(r'trade/code/(?P<pk>[-\w]+)/(?P<code>[-\w]+)/', views.TradeCodeView.as_view(), name='trade_code'),
    re_path(r'trade/detail/(?P<pk>[-\w]+)/(?P<code>[-\w]+)/', views.TradeDetailView.as_view(), name='trade_detail'),
    re_path(r'trade/create/', views.TradeCreateView.as_view(), name='trade_create'),
    # boss
    path('tasks/boss/', views.TaskBossListView.as_view(), name='boss_task_list'),
    path('tasks/boss/delete-requests/', views.delete_request_list_view, name='delete_request_list'),
    re_path(r'tasks/boss/approve/(?P<pk>[-\w]+)/(?P<code>[-\w]+)/', views.TaskBossApproveView.as_view(), name='boss_task_approve'),
    re_path(r'tasks/boss/delete/(?P<pk>[-\w]+)/(?P<code>[-\w]+)/', views.TaskBossDeleteView.as_view(), name='boss_task_delete'),
]


