# Generated by Django 5.1.7 on 2025-03-25 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='district',
            name='title',
        ),
        migrations.RemoveField(
            model_name='subdistrict',
            name='title',
        ),
        migrations.AddField(
            model_name='district',
            name='name',
            field=models.CharField(default='_', max_length=100, verbose_name='District Name'),
        ),
        migrations.AddField(
            model_name='rentfile',
            name='has_image',
            field=models.CharField(blank=True, choices=[('has', 'Has'), ('hasnt', 'Has not')], default='hasnt', max_length=15, null=True, verbose_name='Has Image?'),
        ),
        migrations.AddField(
            model_name='rentfile',
            name='has_video',
            field=models.CharField(blank=True, choices=[('has', 'Has'), ('hasnt', 'Has not')], default='hasnt', max_length=15, null=True, verbose_name='Has Video?'),
        ),
        migrations.AddField(
            model_name='salefile',
            name='has_image',
            field=models.CharField(blank=True, choices=[('has', 'Has'), ('hasnt', 'Has not')], default='hasnt', max_length=15, null=True, verbose_name='Has Image?'),
        ),
        migrations.AddField(
            model_name='salefile',
            name='has_video',
            field=models.CharField(blank=True, choices=[('has', 'Has'), ('hasnt', 'Has not')], default='hasnt', max_length=15, null=True, verbose_name='Has Video?'),
        ),
        migrations.AddField(
            model_name='subdistrict',
            name='name',
            field=models.CharField(default='_', max_length=100, verbose_name='Sub-District Name'),
        ),
    ]
