# Generated by Django 5.1.7 on 2025-03-25 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_remove_district_title_remove_subdistrict_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('OP', 'باز'), ('UR', 'تحویل داده شده'), ('CL', 'بسته')], default='OP', max_length=10, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='task',
            name='type',
            field=models.CharField(choices=[('CS', 'نقد'), ('UC', 'غیر نقد')], max_length=10, verbose_name='Type of Task'),
        ),
    ]
