# Generated by Django 5.1.7 on 2025-03-28 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_task_status_alter_task_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='subdistrict',
            name='description',
            field=models.TextField(blank=True, default='--', max_length=1000, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='customusermodel',
            name='title',
            field=models.CharField(blank=True, choices=[('bs', 'Boss'), ('fp', 'File Person'), ('cp', 'Customer Person')], max_length=10, null=True, verbose_name='Title'),
        ),
    ]
