# Generated by Django 5.1.7 on 2025-03-28 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_subdistrict_description_alter_customusermodel_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subdistrict',
            name='description',
            field=models.TextField(blank=True, default='', max_length=1000, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='subdistrict',
            name='name',
            field=models.CharField(default='', max_length=100, verbose_name='Sub-District Name'),
        ),
    ]
