# Generated by Django 5.1.7 on 2025-03-31 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_subdistrict_description_alter_subdistrict_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentfile',
            name='has_image',
        ),
        migrations.RemoveField(
            model_name='rentfile',
            name='has_video',
        ),
        migrations.RemoveField(
            model_name='salefile',
            name='has_image',
        ),
        migrations.RemoveField(
            model_name='salefile',
            name='has_video',
        ),
    ]
