# Generated by Django 5.1.7 on 2025-04-10 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_remove_rentfile_has_image_remove_rentfile_has_video_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=100, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='person',
            name='description',
            field=models.TextField(blank=True, max_length=150, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(max_length=100, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='rentfile',
            name='balcony',
            field=models.CharField(blank=True, choices=[('has', 'Has'), ('hasnt', 'Has Not')], max_length=15, null=True, verbose_name='Balcony'),
        ),
        migrations.AlterField(
            model_name='rentfile',
            name='bench_stove',
            field=models.CharField(blank=True, choices=[('has', 'Has'), ('hasnt', 'Has Not')], max_length=15, null=True, verbose_name='Bench Stove'),
        ),
        migrations.AlterField(
            model_name='rentfile',
            name='document',
            field=models.CharField(choices=[('has', 'Has'), ('hasnt', 'Has Not')], max_length=15, verbose_name='Document'),
        ),
        migrations.AlterField(
            model_name='rentfile',
            name='elevator',
            field=models.CharField(choices=[('has', 'Has'), ('hasnt', 'Has Not')], max_length=15, verbose_name='Elevator'),
        ),
        migrations.AlterField(
            model_name='rentfile',
            name='parking',
            field=models.CharField(choices=[('has', 'Has'), ('hasnt', 'Has Not')], max_length=15, verbose_name='Parking'),
        ),
        migrations.AlterField(
            model_name='rentfile',
            name='status',
            field=models.CharField(choices=[('acc', 'Accepted'), ('can', 'Canceled'), ('pen', 'Pending')], default='pen', max_length=10, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='rentfile',
            name='warehouse',
            field=models.CharField(choices=[('has', 'Has'), ('hasnt', 'Has Not')], max_length=15, verbose_name='Warehouse'),
        ),
        migrations.AlterField(
            model_name='salefile',
            name='balcony',
            field=models.CharField(blank=True, choices=[('has', 'Has'), ('hasnt', 'Has Not')], max_length=15, null=True, verbose_name='Balcony'),
        ),
        migrations.AlterField(
            model_name='salefile',
            name='bench_stove',
            field=models.CharField(blank=True, choices=[('has', 'Has'), ('hasnt', 'Has Not')], max_length=15, null=True, verbose_name='Bench Stove'),
        ),
        migrations.AlterField(
            model_name='salefile',
            name='document',
            field=models.CharField(choices=[('has', 'Has'), ('hasnt', 'Has Not')], max_length=15, verbose_name='Document'),
        ),
        migrations.AlterField(
            model_name='salefile',
            name='elevator',
            field=models.CharField(choices=[('has', 'Has'), ('hasnt', 'Has Not')], max_length=15, verbose_name='Elevator'),
        ),
        migrations.AlterField(
            model_name='salefile',
            name='parking',
            field=models.CharField(choices=[('has', 'Has'), ('hasnt', 'Has Not')], max_length=15, verbose_name='Parking'),
        ),
        migrations.AlterField(
            model_name='salefile',
            name='status',
            field=models.CharField(choices=[('acc', 'Accepted'), ('can', 'Canceled'), ('pen', 'Pending')], default='pen', max_length=10, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='salefile',
            name='warehouse',
            field=models.CharField(choices=[('has', 'Has'), ('hasnt', 'Has Not')], max_length=15, verbose_name='Warehouse'),
        ),
        migrations.AlterField(
            model_name='session',
            name='status',
            field=models.CharField(choices=[('sub', 'Submitted'), ('can', 'Canceled'), ('dne', 'Done')], default='sub', max_length=10, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('OP', 'باز'), ('UR', 'تحویل داده شده'), ('CL', 'بسته')], default='OP', max_length=10, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='status',
            field=models.CharField(choices=[('sub', 'Submitted'), ('can', 'Canceled'), ('dne', 'Done')], default='sub', max_length=10, verbose_name='وضعیت'),
        ),
    ]
