# Generated by Django 5.1.7 on 2025-04-10 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_person_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='convertable',
            field=models.CharField(blank=True, choices=[('is', 'Is'), ('isnt', 'Is not')], max_length=15, null=True, verbose_name='Convertable'),
        ),
        migrations.AddField(
            model_name='customer',
            name='deposit_announced',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Announced Deposit'),
        ),
        migrations.AddField(
            model_name='customer',
            name='deposit_max',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Max Deposit'),
        ),
        migrations.AddField(
            model_name='customer',
            name='rent_announced',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Announced Rent'),
        ),
        migrations.AddField(
            model_name='customer',
            name='rent_max',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Max Rent'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='budget_announced',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Announced Budget'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='budget_status',
            field=models.CharField(blank=True, choices=[('CS', 'نقد'), ('UC', 'غیر نقد')], max_length=15, null=True, verbose_name='Budget Status'),
        ),
    ]
