# Generated by Django 5.1.7 on 2025-04-10 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_customer_convertable_customer_deposit_announced_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='type',
            field=models.CharField(blank=True, choices=[('sale', 'Sale'), ('rent', 'Rent')], max_length=10, null=True, verbose_name='Type of Customer'),
        ),
    ]
