# Generated by Django 5.1.7 on 2025-04-10 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_customer_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='dashboard.city', verbose_name='City'),
        ),
        migrations.AddField(
            model_name='customer',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='dashboard.district', verbose_name='District'),
        ),
        migrations.AddField(
            model_name='customer',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='dashboard.province', verbose_name='Province'),
        ),
        migrations.AddField(
            model_name='customer',
            name='sub_district1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers_sub_district1', to='dashboard.subdistrict', verbose_name='Sub-District1'),
        ),
        migrations.AddField(
            model_name='customer',
            name='sub_district2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers_sub_district2', to='dashboard.subdistrict', verbose_name='Sub-District2'),
        ),
        migrations.AddField(
            model_name='customer',
            name='sub_district3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers_sub_district3', to='dashboard.subdistrict', verbose_name='Sub-District3'),
        ),
    ]
