# Generated by Django 5.1.7 on 2025-04-10 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_remove_task_customer_buyer_task_buyer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyer',
            name='sub_district1',
        ),
        migrations.RemoveField(
            model_name='buyer',
            name='sub_district2',
        ),
        migrations.RemoveField(
            model_name='buyer',
            name='sub_district3',
        ),
    ]
