# Generated by Django 5.1.7 on 2025-04-18 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_alter_buyer_city_alter_buyer_district_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='name',
            field=models.CharField(default='', max_length=100, verbose_name='District Name'),
        ),
    ]
