# Generated by Django 5.1.7 on 2025-04-23 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_alter_district_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customusermodel',
            name='title',
            field=models.CharField(blank=True, choices=[('bs', 'Boss'), ('fp', 'File Person'), ('cp', 'Customer Person'), ('bt', 'Dual Person')], max_length=10, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='task',
            name='type',
            field=models.CharField(choices=[('fp', 'For File Person'), ('cp', 'For Customer Person'), ('bt', 'For Dual Person')], max_length=10, verbose_name='Type of Task'),
        ),
    ]
