# Generated by Django 5.1.7 on 2025-04-23 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_task_slug_alter_customusermodel_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='renter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='dashboard.renter', verbose_name='Renter'),
        ),
    ]
