# Generated by Django 5.1.7 on 2025-04-23 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_task_renter'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='sub_district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='dashboard.subdistrict', verbose_name='Sub-District'),
        ),
    ]
