# Generated by Django 5.1.7 on 2025-04-26 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_task_sub_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusermodel',
            name='sub_district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agents', to='dashboard.subdistrict', verbose_name='Sub-District'),
        ),
    ]
