# Generated by Django 5.1.7 on 2025-04-26 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_customusermodel_sub_district'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='sub_district',
        ),
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.CharField(max_length=200, verbose_name='Deadline'),
        ),
    ]
