# Generated by Django 5.1.7 on 2025-04-26 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_remove_task_sub_district_alter_task_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='sub_districts',
            field=models.ManyToManyField(blank=True, related_name='buyers', to='dashboard.subdistrict', verbose_name='Sub-Districts'),
        ),
    ]
