# Generated by Django 5.1.7 on 2025-04-27 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0021_buyer_sub_districts'),
    ]

    operations = [
        migrations.AddField(
            model_name='renter',
            name='sub_districts',
            field=models.ManyToManyField(blank=True, related_name='renters', to='dashboard.subdistrict', verbose_name='Sub-Districts'),
        ),
    ]
