# Generated by Django 5.1.7 on 2025-05-05 17:32

import dashboard.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0022_renter_sub_districts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='rentfile',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='salefile',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='task',
            name='slug',
        ),
        migrations.AlterField(
            model_name='buyer',
            name='age_max',
            field=models.CharField(choices=[('-1', 'کلید نخورده'), ('0', 'نوساز'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('23', '23'), ('24', '24'), ('25', '25'), ('26', '26'), ('27', '27'), ('28', '28'), ('29', '29'), ('30', '30'), ('31', 'بیش از 30')], default='1', max_length=15, verbose_name='حداکثر سن'),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='age_min',
            field=models.CharField(choices=[('-1', 'کلید نخورده'), ('0', 'نوساز'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('23', '23'), ('24', '24'), ('25', '25'), ('26', '26'), ('27', '27'), ('28', '28'), ('29', '29'), ('30', '30'), ('31', 'بیش از 30')], default='1', max_length=15, verbose_name='حداقل سن'),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='area_max',
            field=models.PositiveIntegerField(default='1', verbose_name='حداکثر متراژ'),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='area_min',
            field=models.PositiveIntegerField(default='1', verbose_name='حداقل متراژ'),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='budget_announced',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='بودجه اعلامی'),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='budget_max',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='حداکثر بودجه'),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='budget_status',
            field=models.CharField(blank=True, choices=[('CS', 'نقد'), ('UC', 'غیر نقد')], max_length=15, null=True, verbose_name='وضعیت بودجه'),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buyers', to='dashboard.city', verbose_name='شهر'),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='code',
            field=models.CharField(blank=True, max_length=6, null=True, unique=True, verbose_name='کد'),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='datetime_created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ و زمان ایجاد'),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='description',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buyers', to='dashboard.district', verbose_name='منطقه (محله)'),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='document',
            field=models.CharField(choices=[('has', 'Has'), ('hasnt', 'Has Not')], max_length=15, verbose_name='سند'),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='elevator',
            field=models.CharField(choices=[('has', 'Has'), ('hasnt', 'Has Not')], max_length=15, verbose_name='آسانسور'),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='parking',
            field=models.CharField(choices=[('has', 'Has'), ('hasnt', 'Has Not')], max_length=15, verbose_name='پارکینگ'),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='phone_number',
            field=models.CharField(max_length=11, unique=True, verbose_name='تلفن همراه'),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buyers', to='dashboard.province', verbose_name='استان'),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='room_max',
            field=models.CharField(choices=[('0', 'بدون اتاق'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', 'بیش از 5')], max_length=15, verbose_name='حداکثر تعداد اتاق'),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='room_min',
            field=models.CharField(choices=[('0', 'بدون اتاق'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', 'بیش از 5')], max_length=15, verbose_name='حداقل تعداد اتاق'),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='sub_districts',
            field=models.ManyToManyField(blank=True, related_name='buyers', to='dashboard.subdistrict', verbose_name='زیرمحله\u200cها'),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='warehouse',
            field=models.CharField(choices=[('has', 'Has'), ('hasnt', 'Has Not')], max_length=15, verbose_name='انباری'),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=100, verbose_name='شهر'),
        ),
        migrations.AlterField(
            model_name='customusermodel',
            name='sub_district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agents', to='dashboard.subdistrict', verbose_name='زیرمحله'),
        ),
        migrations.AlterField(
            model_name='customusermodel',
            name='title',
            field=models.CharField(blank=True, choices=[('bs', 'مدیر'), ('fp', 'مشاور فایل\u200cها'), ('cp', 'مشاور مشتریان'), ('bt', 'مشاور دوگانه')], max_length=10, null=True, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='district',
            name='name',
            field=models.CharField(default='', max_length=100, verbose_name='نام منطقه (محله)'),
        ),
        migrations.AlterField(
            model_name='person',
            name='description',
            field=models.TextField(blank=True, max_length=150, null=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='person',
            name='phone_number',
            field=models.CharField(max_length=11, unique=True, verbose_name='تلفن همراه'),
        ),
        migrations.AlterField(
            model_name='province',
            name='name',
            field=models.CharField(max_length=100, verbose_name='استان'),
        ),
        migrations.AlterField(
            model_name='renter',
            name='age_max',
            field=models.CharField(choices=[('-1', 'کلید نخورده'), ('0', 'نوساز'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('23', '23'), ('24', '24'), ('25', '25'), ('26', '26'), ('27', '27'), ('28', '28'), ('29', '29'), ('30', '30'), ('31', 'بیش از 30')], default='1', max_length=15, verbose_name='حداکثر سن'),
        ),
        migrations.AlterField(
            model_name='renter',
            name='age_min',
            field=models.CharField(choices=[('-1', 'کلید نخورده'), ('0', 'نوساز'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('23', '23'), ('24', '24'), ('25', '25'), ('26', '26'), ('27', '27'), ('28', '28'), ('29', '29'), ('30', '30'), ('31', 'بیش از 30')], default='1', max_length=15, verbose_name='حداقل سن'),
        ),
        migrations.AlterField(
            model_name='renter',
            name='area_max',
            field=models.PositiveIntegerField(default='1', verbose_name='حداکثر متراژ'),
        ),
        migrations.AlterField(
            model_name='renter',
            name='area_min',
            field=models.PositiveIntegerField(default='1', verbose_name='حداقل متراژ'),
        ),
        migrations.AlterField(
            model_name='renter',
            name='budget_status',
            field=models.CharField(blank=True, choices=[('CS', 'نقد'), ('UC', 'غیر نقد')], max_length=15, null=True, verbose_name='وضعیت بودجه'),
        ),
        migrations.AlterField(
            model_name='renter',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='renters', to='dashboard.city', verbose_name='شهر'),
        ),
        migrations.AlterField(
            model_name='renter',
            name='code',
            field=models.CharField(blank=True, max_length=6, null=True, unique=True, verbose_name='کد'),
        ),
        migrations.AlterField(
            model_name='renter',
            name='convertable',
            field=models.CharField(choices=[('is', 'هست'), ('isnt', 'نیست')], max_length=15, verbose_name='قابل تبدیل'),
        ),
        migrations.AlterField(
            model_name='renter',
            name='datetime_created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ و زمان ایجاد'),
        ),
        migrations.AlterField(
            model_name='renter',
            name='deposit_announced',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='ودیعه اعلامی'),
        ),
        migrations.AlterField(
            model_name='renter',
            name='deposit_max',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='حداکثر ودیعه'),
        ),
        migrations.AlterField(
            model_name='renter',
            name='description',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='renter',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='renters', to='dashboard.district', verbose_name='منطقه (محله)'),
        ),
        migrations.AlterField(
            model_name='renter',
            name='document',
            field=models.CharField(choices=[('has', 'Has'), ('hasnt', 'Has Not')], max_length=15, verbose_name='سند'),
        ),
        migrations.AlterField(
            model_name='renter',
            name='elevator',
            field=models.CharField(choices=[('has', 'Has'), ('hasnt', 'Has Not')], max_length=15, verbose_name='آسانسور'),
        ),
        migrations.AlterField(
            model_name='renter',
            name='parking',
            field=models.CharField(choices=[('has', 'Has'), ('hasnt', 'Has Not')], max_length=15, verbose_name='پارکینگ'),
        ),
        migrations.AlterField(
            model_name='renter',
            name='phone_number',
            field=models.CharField(max_length=11, unique=True, verbose_name='تلفن همراه'),
        ),
        migrations.AlterField(
            model_name='renter',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='renters', to='dashboard.province', verbose_name='استان'),
        ),
        migrations.AlterField(
            model_name='renter',
            name='rent_announced',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='اجاره اعلامی'),
        ),
        migrations.AlterField(
            model_name='renter',
            name='rent_max',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='حداکثر اجاره'),
        ),
        migrations.AlterField(
            model_name='renter',
            name='room_max',
            field=models.CharField(choices=[('0', 'بدون اتاق'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', 'بیش از 5')], max_length=15, verbose_name='حداکثر تعداد اتاق'),
        ),
        migrations.AlterField(
            model_name='renter',
            name='room_min',
            field=models.CharField(choices=[('0', 'بدون اتاق'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', 'بیش از 5')], max_length=15, verbose_name='حداقل تعداد اتاق'),
        ),
        migrations.AlterField(
            model_name='renter',
            name='sub_districts',
            field=models.ManyToManyField(blank=True, related_name='renters', to='dashboard.subdistrict', verbose_name='زیرمحله\u200cها'),
        ),
        migrations.AlterField(
            model_name='renter',
            name='warehouse',
            field=models.CharField(choices=[('has', 'Has'), ('hasnt', 'Has Not')], max_length=15, verbose_name='انباری'),
        ),
        migrations.AlterField(
            model_name='rentfile',
            name='address',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='rentfile',
            name='age',
            field=models.CharField(choices=[('-1', 'کلید نخورده'), ('0', 'نوساز'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('23', '23'), ('24', '24'), ('25', '25'), ('26', '26'), ('27', '27'), ('28', '28'), ('29', '29'), ('30', '30'), ('31', 'بیش از 30')], default='1', max_length=15, verbose_name='سن آپارتمان'),
        ),
        migrations.AlterField(
            model_name='rentfile',
            name='apartments_per_level',
            field=models.CharField(blank=True, choices=[('one', 'تک واحدی'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('more-10', 'بیش از 10')], max_length=15, null=True, verbose_name='تعداد واحد در طبقه'),
        ),
        migrations.AlterField(
            model_name='rentfile',
            name='area',
            field=models.PositiveIntegerField(verbose_name='متراژ'),
        ),
        migrations.AlterField(
            model_name='rentfile',
            name='balcony',
            field=models.CharField(blank=True, choices=[('has', 'Has'), ('hasnt', 'Has Not')], max_length=15, null=True, verbose_name='بالکن'),
        ),
        migrations.AlterField(
            model_name='rentfile',
            name='bench_stove',
            field=models.CharField(blank=True, choices=[('has', 'Has'), ('hasnt', 'Has Not')], max_length=15, null=True, verbose_name='گاز رومیزی'),
        ),
        migrations.AlterField(
            model_name='rentfile',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rent_files', to='dashboard.city', verbose_name='شهر'),
        ),
        migrations.AlterField(
            model_name='rentfile',
            name='code',
            field=models.CharField(blank=True, max_length=6, null=True, unique=True, verbose_name='کد'),
        ),
        migrations.AlterField(
            model_name='rentfile',
            name='convertable',
            field=models.CharField(choices=[('is', 'هست'), ('isnt', 'نیست')], max_length=15, verbose_name='قابل تبدیل'),
        ),
        migrations.AlterField(
            model_name='rentfile',
            name='cooling',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='سیستم سرمایش'),
        ),
        migrations.AlterField(
            model_name='rentfile',
            name='deposit_announced',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='ودیعه اعلامی'),
        ),
        migrations.AlterField(
            model_name='rentfile',
            name='deposit_min',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='حداقل ودیعه'),
        ),
        migrations.AlterField(
            model_name='rentfile',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='rentfile',
            name='direction',
            field=models.CharField(blank=True, choices=[('nth', 'شمالی'), ('sth', 'جنوبی'), ('est', 'شرقی'), ('wst', 'غربی')], max_length=15, null=True, verbose_name='جهت ملک'),
        ),
        migrations.AlterField(
            model_name='rentfile',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rent_files', to='dashboard.district', verbose_name='منطقه (محله)'),
        ),
        migrations.AlterField(
            model_name='rentfile',
            name='document',
            field=models.CharField(choices=[('has', 'Has'), ('hasnt', 'Has Not')], max_length=15, verbose_name='سند'),
        ),
        migrations.AlterField(
            model_name='rentfile',
            name='elevator',
            field=models.CharField(choices=[('has', 'Has'), ('hasnt', 'Has Not')], max_length=15, verbose_name='آسانسور'),
        ),
        migrations.AlterField(
            model_name='rentfile',
            name='file_levels',
            field=models.CharField(blank=True, choices=[('-1', 'زیر همکف'), ('0', 'همکف'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('23', '23'), ('24', '24'), ('25', '25'), ('26', '26'), ('27', '27'), ('28', '28'), ('29', '29'), ('30', '30'), ('31', 'بالاتر از 30')], max_length=15, null=True, verbose_name='تعداد طبقات ساختمان'),
        ),
        migrations.AlterField(
            model_name='rentfile',
            name='floor',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='جنس کف'),
        ),
        migrations.AlterField(
            model_name='rentfile',
            name='heating',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='سیستم گرمایش'),
        ),
        migrations.AlterField(
            model_name='rentfile',
            name='hot_water',
            field=models.CharField(blank=True, choices=[('HW', 'آبگرم\u200cکن'), ('MH', 'موتورخانه'), ('PK', 'پکیج'), ('OT', 'سایر')], max_length=15, null=True, verbose_name='سیستم تامین آب گرم'),
        ),
        migrations.AlterField(
            model_name='rentfile',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='files/images/', verbose_name='تصویر اول'),
        ),
        migrations.AlterField(
            model_name='rentfile',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='files/images/', verbose_name='تصویر دوم'),
        ),
        migrations.AlterField(
            model_name='rentfile',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='files/images/', verbose_name='تصویر سوم'),
        ),
        migrations.AlterField(
            model_name='rentfile',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='files/images/', verbose_name='تصویر چهارم'),
        ),
        migrations.AlterField(
            model_name='rentfile',
            name='image5',
            field=models.ImageField(blank=True, null=True, upload_to='files/images/', verbose_name='تصویر پنجم'),
        ),
        migrations.AlterField(
            model_name='rentfile',
            name='image6',
            field=models.ImageField(blank=True, null=True, upload_to='files/images/', verbose_name='تصویر ششم'),
        ),
        migrations.AlterField(
            model_name='rentfile',
            name='image7',
            field=models.ImageField(blank=True, null=True, upload_to='files/images/', verbose_name='تصویر هفتم'),
        ),
        migrations.AlterField(
            model_name='rentfile',
            name='image8',
            field=models.ImageField(blank=True, null=True, upload_to='files/images/', verbose_name='تصویر هشتم'),
        ),
        migrations.AlterField(
            model_name='rentfile',
            name='image9',
            field=models.ImageField(blank=True, null=True, upload_to='files/images/', verbose_name='تصویر نهم'),
        ),
        migrations.AlterField(
            model_name='rentfile',
            name='level',
            field=models.CharField(choices=[('-1', 'زیر همکف'), ('0', 'همکف'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('23', '23'), ('24', '24'), ('25', '25'), ('26', '26'), ('27', '27'), ('28', '28'), ('29', '29'), ('30', '30'), ('31', 'بالاتر از 30')], max_length=15, verbose_name='طبقه'),
        ),
        migrations.AlterField(
            model_name='rentfile',
            name='parking',
            field=models.CharField(choices=[('has', 'Has'), ('hasnt', 'Has Not')], max_length=15, verbose_name='پارکینگ'),
        ),
        migrations.AlterField(
            model_name='rentfile',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rent_files', to='dashboard.person', verbose_name='شخص آگهی\u200cدهنده'),
        ),
        migrations.AlterField(
            model_name='rentfile',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rent_files', to='dashboard.province', verbose_name='استان'),
        ),
        migrations.AlterField(
            model_name='rentfile',
            name='rent_announced',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='اجاره اعلامی'),
        ),
        migrations.AlterField(
            model_name='rentfile',
            name='rent_min',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='حداقل اجاره'),
        ),
        migrations.AlterField(
            model_name='rentfile',
            name='restoration',
            field=models.CharField(blank=True, choices=[('done', 'انجام \u200cشده'), ('dont', 'انجام \u200cنشده')], max_length=15, null=True, verbose_name='وضعیت بازسازی'),
        ),
        migrations.AlterField(
            model_name='rentfile',
            name='room',
            field=models.CharField(choices=[('0', 'بدون اتاق'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', 'بیش از 5')], max_length=15, verbose_name='تعداد اتاق'),
        ),
        migrations.AlterField(
            model_name='rentfile',
            name='source',
            field=models.CharField(blank=True, choices=[('DV', 'دیوار'), ('KS', 'کاشانو'), ('SK', 'اسکان'), ('OT', 'سایر'), ('PN', 'شخص')], max_length=15, null=True, verbose_name='منبع'),
        ),
        migrations.AlterField(
            model_name='rentfile',
            name='status',
            field=models.CharField(choices=[('acc', 'پذیرفته \u200cشده'), ('can', 'رد شده'), ('pen', 'در انتظار')], default='pen', max_length=10, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='rentfile',
            name='sub_district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rent_files', to='dashboard.subdistrict', verbose_name='زیرمحله'),
        ),
        migrations.AlterField(
            model_name='rentfile',
            name='title',
            field=models.CharField(max_length=230, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='rentfile',
            name='toilet',
            field=models.CharField(blank=True, choices=[('IR', 'ایرانی'), ('FG', 'فرنگی'), ('BT', 'هر دو')], max_length=15, null=True, verbose_name='سرویس بهداشتی'),
        ),
        migrations.AlterField(
            model_name='rentfile',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/', verbose_name='ویدئو'),
        ),
        migrations.AlterField(
            model_name='rentfile',
            name='warehouse',
            field=models.CharField(choices=[('has', 'Has'), ('hasnt', 'Has Not')], max_length=15, verbose_name='انباری'),
        ),
        migrations.AlterField(
            model_name='salefile',
            name='address',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='salefile',
            name='age',
            field=models.CharField(choices=[('-1', 'کلید نخورده'), ('0', 'نوساز'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('23', '23'), ('24', '24'), ('25', '25'), ('26', '26'), ('27', '27'), ('28', '28'), ('29', '29'), ('30', '30'), ('31', 'بیش از 30')], default='1', max_length=15, verbose_name='سن آپارتمان'),
        ),
        migrations.AlterField(
            model_name='salefile',
            name='apartments_per_level',
            field=models.CharField(blank=True, choices=[('one', 'تک واحدی'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('more-10', 'بیش از 10')], max_length=15, null=True, verbose_name='تعداد واحد در طبقه'),
        ),
        migrations.AlterField(
            model_name='salefile',
            name='area',
            field=models.PositiveIntegerField(verbose_name='متراژ'),
        ),
        migrations.AlterField(
            model_name='salefile',
            name='balcony',
            field=models.CharField(blank=True, choices=[('has', 'Has'), ('hasnt', 'Has Not')], max_length=15, null=True, verbose_name='بالکن'),
        ),
        migrations.AlterField(
            model_name='salefile',
            name='bench_stove',
            field=models.CharField(blank=True, choices=[('has', 'Has'), ('hasnt', 'Has Not')], max_length=15, null=True, verbose_name='گاز رومیزی'),
        ),
        migrations.AlterField(
            model_name='salefile',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_files', to='dashboard.city', verbose_name='شهر'),
        ),
        migrations.AlterField(
            model_name='salefile',
            name='code',
            field=models.CharField(blank=True, max_length=6, null=True, unique=True, verbose_name='کد'),
        ),
        migrations.AlterField(
            model_name='salefile',
            name='cooling',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='سیستم سرمایش'),
        ),
        migrations.AlterField(
            model_name='salefile',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='salefile',
            name='direction',
            field=models.CharField(blank=True, choices=[('nth', 'شمالی'), ('sth', 'جنوبی'), ('est', 'شرقی'), ('wst', 'غربی')], max_length=15, null=True, verbose_name='جهت ملک'),
        ),
        migrations.AlterField(
            model_name='salefile',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_files', to='dashboard.district', verbose_name='منطقه (محله)'),
        ),
        migrations.AlterField(
            model_name='salefile',
            name='document',
            field=models.CharField(choices=[('has', 'Has'), ('hasnt', 'Has Not')], max_length=15, verbose_name='سند'),
        ),
        migrations.AlterField(
            model_name='salefile',
            name='elevator',
            field=models.CharField(choices=[('has', 'Has'), ('hasnt', 'Has Not')], max_length=15, verbose_name='آسانسور'),
        ),
        migrations.AlterField(
            model_name='salefile',
            name='file_levels',
            field=models.CharField(blank=True, choices=[('-1', 'زیر همکف'), ('0', 'همکف'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('23', '23'), ('24', '24'), ('25', '25'), ('26', '26'), ('27', '27'), ('28', '28'), ('29', '29'), ('30', '30'), ('31', 'بالاتر از 30')], max_length=15, null=True, verbose_name='تعداد طبقات ساختمان'),
        ),
        migrations.AlterField(
            model_name='salefile',
            name='floor',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='جنس کف'),
        ),
        migrations.AlterField(
            model_name='salefile',
            name='heating',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='سیستم گرمایش'),
        ),
        migrations.AlterField(
            model_name='salefile',
            name='hot_water',
            field=models.CharField(blank=True, choices=[('HW', 'آبگرم\u200cکن'), ('MH', 'موتورخانه'), ('PK', 'پکیج'), ('OT', 'سایر')], max_length=15, null=True, verbose_name='سیستم تامین آب گرم'),
        ),
        migrations.AlterField(
            model_name='salefile',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='files/images/', verbose_name='تصویر اول'),
        ),
        migrations.AlterField(
            model_name='salefile',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='files/images/', verbose_name='تصویر دوم'),
        ),
        migrations.AlterField(
            model_name='salefile',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='files/images/', verbose_name='تصویر سوم'),
        ),
        migrations.AlterField(
            model_name='salefile',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='files/images/', verbose_name='تصویر چهارم'),
        ),
        migrations.AlterField(
            model_name='salefile',
            name='image5',
            field=models.ImageField(blank=True, null=True, upload_to='files/images/', verbose_name='تصویر پنجم'),
        ),
        migrations.AlterField(
            model_name='salefile',
            name='image6',
            field=models.ImageField(blank=True, null=True, upload_to='files/images/', verbose_name='تصویر ششم'),
        ),
        migrations.AlterField(
            model_name='salefile',
            name='image7',
            field=models.ImageField(blank=True, null=True, upload_to='files/images/', verbose_name='تصویر هفتم'),
        ),
        migrations.AlterField(
            model_name='salefile',
            name='image8',
            field=models.ImageField(blank=True, null=True, upload_to='files/images/', verbose_name='تصویر هشتم'),
        ),
        migrations.AlterField(
            model_name='salefile',
            name='image9',
            field=models.ImageField(blank=True, null=True, upload_to='files/images/', verbose_name='تصویر نهم'),
        ),
        migrations.AlterField(
            model_name='salefile',
            name='level',
            field=models.CharField(choices=[('-1', 'زیر همکف'), ('0', 'همکف'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('23', '23'), ('24', '24'), ('25', '25'), ('26', '26'), ('27', '27'), ('28', '28'), ('29', '29'), ('30', '30'), ('31', 'بالاتر از 30')], max_length=15, verbose_name='طبقه'),
        ),
        migrations.AlterField(
            model_name='salefile',
            name='parking',
            field=models.CharField(choices=[('has', 'Has'), ('hasnt', 'Has Not')], max_length=15, verbose_name='پارکینگ'),
        ),
        migrations.AlterField(
            model_name='salefile',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_files', to='dashboard.person', verbose_name='شخص آگهی\u200cدهنده'),
        ),
        migrations.AlterField(
            model_name='salefile',
            name='price_announced',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='قیمت اعلامی'),
        ),
        migrations.AlterField(
            model_name='salefile',
            name='price_min',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='حداقل قیمت'),
        ),
        migrations.AlterField(
            model_name='salefile',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_files', to='dashboard.province', verbose_name='استان'),
        ),
        migrations.AlterField(
            model_name='salefile',
            name='restoration',
            field=models.CharField(blank=True, choices=[('done', 'انجام \u200cشده'), ('dont', 'انجام \u200cنشده')], max_length=15, null=True, verbose_name='وضعیت بازسازی'),
        ),
        migrations.AlterField(
            model_name='salefile',
            name='room',
            field=models.CharField(choices=[('0', 'بدون اتاق'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', 'بیش از 5')], max_length=15, verbose_name='تعداد اتاق'),
        ),
        migrations.AlterField(
            model_name='salefile',
            name='source',
            field=models.CharField(blank=True, choices=[('DV', 'دیوار'), ('KS', 'کاشانو'), ('SK', 'اسکان'), ('OT', 'سایر'), ('PN', 'شخص')], max_length=15, null=True, verbose_name='منبع'),
        ),
        migrations.AlterField(
            model_name='salefile',
            name='status',
            field=models.CharField(choices=[('acc', 'پذیرفته \u200cشده'), ('can', 'رد شده'), ('pen', 'در انتظار')], default='pen', max_length=10, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='salefile',
            name='sub_district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_files', to='dashboard.subdistrict', verbose_name='زیرمحله'),
        ),
        migrations.AlterField(
            model_name='salefile',
            name='title',
            field=models.CharField(max_length=230, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='salefile',
            name='toilet',
            field=models.CharField(blank=True, choices=[('IR', 'ایرانی'), ('FG', 'فرنگی'), ('BT', 'هر دو')], max_length=15, null=True, verbose_name='سرویس بهداشتی'),
        ),
        migrations.AlterField(
            model_name='salefile',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/', verbose_name='ویدئو'),
        ),
        migrations.AlterField(
            model_name='salefile',
            name='warehouse',
            field=models.CharField(choices=[('has', 'Has'), ('hasnt', 'Has Not')], max_length=15, verbose_name='انباری'),
        ),
        migrations.AlterField(
            model_name='session',
            name='code',
            field=models.CharField(blank=True, max_length=6, null=True, unique=True, verbose_name='کد'),
        ),
        migrations.AlterField(
            model_name='session',
            name='date',
            field=models.CharField(max_length=200, verbose_name='تاریخ بازدید'),
        ),
        migrations.AlterField(
            model_name='session',
            name='datetime_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ و زمان ایجاد'),
        ),
        migrations.AlterField(
            model_name='session',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='session',
            name='result',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='نتیجه'),
        ),
        migrations.AlterField(
            model_name='session',
            name='status',
            field=models.CharField(choices=[('sub', 'ثبت شده'), ('can', 'رد شده'), ('dne', 'انجام \u200cشده')], default='sub', max_length=10, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='session',
            name='time',
            field=models.CharField(choices=[('mg', 'صبح'), ('nn', 'ظهر'), ('eg', 'عصر'), ('nt', 'شب')], max_length=200, verbose_name='زمان بازدید'),
        ),
        migrations.AlterField(
            model_name='session',
            name='type',
            field=models.CharField(max_length=10, verbose_name='نوع معامله'),
        ),
        migrations.AlterField(
            model_name='session',
            name='visit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='dashboard.visit', verbose_name='بازدید مربوطه'),
        ),
        migrations.AlterField(
            model_name='subdistrict',
            name='description',
            field=models.TextField(blank=True, default='', max_length=1000, null=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='subdistrict',
            name='name',
            field=models.CharField(default='', max_length=100, verbose_name='نام زیرمحله'),
        ),
        migrations.AlterField(
            model_name='task',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to=settings.AUTH_USER_MODEL, verbose_name='مشاور'),
        ),
        migrations.AlterField(
            model_name='task',
            name='buyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='dashboard.buyer', verbose_name='خریدار'),
        ),
        migrations.AlterField(
            model_name='task',
            name='datetime_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ و زمان ایجاد'),
        ),
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.CharField(max_length=200, verbose_name='مهلت انجام'),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='task',
            name='rent_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='dashboard.rentfile', verbose_name='فایل اجاره'),
        ),
        migrations.AlterField(
            model_name='task',
            name='renter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='dashboard.renter', verbose_name='موجر'),
        ),
        migrations.AlterField(
            model_name='task',
            name='result',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='نتیجه'),
        ),
        migrations.AlterField(
            model_name='task',
            name='sale_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='dashboard.salefile', verbose_name='فایل فروش'),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=200, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='task',
            name='type',
            field=models.CharField(choices=[('fp', 'برای مشاور فایل\u200cها'), ('cp', 'برای مشاور مشتریان'), ('bt', 'برای مشاور دوگانه')], max_length=10, verbose_name='نوع وظیفه'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='code',
            field=models.CharField(blank=True, max_length=6, null=True, unique=True, verbose_name='کد'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='customer',
            field=models.CharField(max_length=100, verbose_name='مشتری (خریدار / مستاجر)'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='customer_national_code',
            field=models.CharField(max_length=10, verbose_name='کد ملی مشتری'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='date',
            field=models.CharField(choices=dashboard.models.last_month_shamsi, max_length=200, verbose_name='تاریخ معامله'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='datetime_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ و زمان ایجاد'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='deposit',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='ودیعه'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='followup_code',
            field=models.CharField(blank=True, max_length=6, null=True, unique=True, verbose_name='کد پیگیری'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='owner',
            field=models.CharField(max_length=100, verbose_name='مالک (فروشنده / موجر)'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='owner_national_code',
            field=models.CharField(max_length=10, verbose_name='کد ملی مالک'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='price',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='قیمت'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='rent',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='اجاره'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trades', to='dashboard.session', verbose_name='نشست مربوطه'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='type',
            field=models.CharField(max_length=10, verbose_name='نوع معامله'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='code',
            field=models.CharField(blank=True, max_length=6, null=True, unique=True, verbose_name='کد'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits', to='dashboard.buyer', verbose_name='خریدار'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='date',
            field=models.CharField(max_length=200, verbose_name='تاریخ بازدید'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='datetime_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ و زمان ایجاد'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='rent_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits', to='dashboard.rentfile', verbose_name='فایل اجاره'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='result',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='نتیجه'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='sale_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits', to='dashboard.salefile', verbose_name='فایل فروش'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='status',
            field=models.CharField(choices=[('sub', 'ثبت شده'), ('can', 'رد شده'), ('dne', 'انجام \u200cشده')], default='sub', max_length=10, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='time',
            field=models.CharField(choices=[('mg', 'صبح'), ('nn', 'ظهر'), ('eg', 'عصر'), ('nt', 'شب')], max_length=200, verbose_name='زمان بازدید'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='type',
            field=models.CharField(max_length=10, verbose_name='نوع معامله'),
        ),
    ]
