# Generated by Django 5.1.7 on 2025-05-05 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0024_alter_trade_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trade',
            name='customer',
        ),
        migrations.AddField(
            model_name='trade',
            name='buyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.buyer', verbose_name='Customer (Buyer)'),
        ),
        migrations.AddField(
            model_name='trade',
            name='renter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.renter', verbose_name='Customer (Renter)'),
        ),
    ]
