# Generated by Django 5.1.7 on 2025-05-19 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0025_remove_trade_customer_trade_buyer_trade_renter'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buyer',
            options={'ordering': ('-datetime_created',), 'verbose_name': 'خریدار', 'verbose_name_plural': 'خریداران'},
        ),
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': 'شهر', 'verbose_name_plural': 'شهرها'},
        ),
        migrations.AlterModelOptions(
            name='district',
            options={'verbose_name': 'محله (منطقه)', 'verbose_name_plural': 'محلات (مناطق)'},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': 'شخص آگهی\u200cدهنده', 'verbose_name_plural': 'اشخاص آگهی\u200cدهنده'},
        ),
        migrations.AlterModelOptions(
            name='province',
            options={'verbose_name': 'استان', 'verbose_name_plural': 'استان\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='renter',
            options={'ordering': ('-datetime_created',), 'verbose_name': 'مستاجر', 'verbose_name_plural': 'مستاجران'},
        ),
        migrations.AlterModelOptions(
            name='rentfile',
            options={'ordering': ('-datetime_created',), 'verbose_name': 'فایل اجاره', 'verbose_name_plural': 'فایل\u200cهای اجاره'},
        ),
        migrations.AlterModelOptions(
            name='salefile',
            options={'ordering': ('-datetime_created',), 'verbose_name': 'فایل فروش', 'verbose_name_plural': 'فایل\u200cهای فروش'},
        ),
        migrations.AlterModelOptions(
            name='session',
            options={'ordering': ('-datetime_created',), 'verbose_name': 'نشست', 'verbose_name_plural': 'نشست\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='subdistrict',
            options={'verbose_name': 'زیرمحله', 'verbose_name_plural': 'زیرمحلات'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ('-datetime_created',), 'verbose_name': 'وظیفه', 'verbose_name_plural': 'وظایف'},
        ),
        migrations.AlterModelOptions(
            name='trade',
            options={'ordering': ('-datetime_created',), 'verbose_name': 'معامله', 'verbose_name_plural': 'معاملات'},
        ),
        migrations.AlterModelOptions(
            name='visit',
            options={'ordering': ('-datetime_created',), 'verbose_name': 'بازدید', 'verbose_name_plural': 'بازدیدها'},
        ),
        migrations.AddField(
            model_name='buyer',
            name='status',
            field=models.CharField(choices=[('acc', 'پذیرفته \u200cشده'), ('can', 'رد شده'), ('pen', 'در انتظار')], default='pen', max_length=10, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='document',
            field=models.CharField(choices=[('has', 'دارد'), ('hasnt', 'ندارد')], max_length=15, verbose_name='سند'),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='elevator',
            field=models.CharField(choices=[('has', 'دارد'), ('hasnt', 'ندارد')], max_length=15, verbose_name='آسانسور'),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='parking',
            field=models.CharField(choices=[('has', 'دارد'), ('hasnt', 'ندارد')], max_length=15, verbose_name='پارکینگ'),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='warehouse',
            field=models.CharField(choices=[('has', 'دارد'), ('hasnt', 'ندارد')], max_length=15, verbose_name='انباری'),
        ),
        migrations.AlterField(
            model_name='renter',
            name='document',
            field=models.CharField(choices=[('has', 'دارد'), ('hasnt', 'ندارد')], max_length=15, verbose_name='سند'),
        ),
        migrations.AlterField(
            model_name='renter',
            name='elevator',
            field=models.CharField(choices=[('has', 'دارد'), ('hasnt', 'ندارد')], max_length=15, verbose_name='آسانسور'),
        ),
        migrations.AlterField(
            model_name='renter',
            name='parking',
            field=models.CharField(choices=[('has', 'دارد'), ('hasnt', 'ندارد')], max_length=15, verbose_name='پارکینگ'),
        ),
        migrations.AlterField(
            model_name='renter',
            name='warehouse',
            field=models.CharField(choices=[('has', 'دارد'), ('hasnt', 'ندارد')], max_length=15, verbose_name='انباری'),
        ),
        migrations.AlterField(
            model_name='rentfile',
            name='balcony',
            field=models.CharField(blank=True, choices=[('has', 'دارد'), ('hasnt', 'ندارد')], max_length=15, null=True, verbose_name='بالکن'),
        ),
        migrations.AlterField(
            model_name='rentfile',
            name='bench_stove',
            field=models.CharField(blank=True, choices=[('has', 'دارد'), ('hasnt', 'ندارد')], max_length=15, null=True, verbose_name='گاز رومیزی'),
        ),
        migrations.AlterField(
            model_name='rentfile',
            name='document',
            field=models.CharField(choices=[('has', 'دارد'), ('hasnt', 'ندارد')], max_length=15, verbose_name='سند'),
        ),
        migrations.AlterField(
            model_name='rentfile',
            name='elevator',
            field=models.CharField(choices=[('has', 'دارد'), ('hasnt', 'ندارد')], max_length=15, verbose_name='آسانسور'),
        ),
        migrations.AlterField(
            model_name='rentfile',
            name='parking',
            field=models.CharField(choices=[('has', 'دارد'), ('hasnt', 'ندارد')], max_length=15, verbose_name='پارکینگ'),
        ),
        migrations.AlterField(
            model_name='rentfile',
            name='warehouse',
            field=models.CharField(choices=[('has', 'دارد'), ('hasnt', 'ندارد')], max_length=15, verbose_name='انباری'),
        ),
        migrations.AlterField(
            model_name='salefile',
            name='balcony',
            field=models.CharField(blank=True, choices=[('has', 'دارد'), ('hasnt', 'ندارد')], max_length=15, null=True, verbose_name='بالکن'),
        ),
        migrations.AlterField(
            model_name='salefile',
            name='bench_stove',
            field=models.CharField(blank=True, choices=[('has', 'دارد'), ('hasnt', 'ندارد')], max_length=15, null=True, verbose_name='گاز رومیزی'),
        ),
        migrations.AlterField(
            model_name='salefile',
            name='document',
            field=models.CharField(choices=[('has', 'دارد'), ('hasnt', 'ندارد')], max_length=15, verbose_name='سند'),
        ),
        migrations.AlterField(
            model_name='salefile',
            name='elevator',
            field=models.CharField(choices=[('has', 'دارد'), ('hasnt', 'ندارد')], max_length=15, verbose_name='آسانسور'),
        ),
        migrations.AlterField(
            model_name='salefile',
            name='parking',
            field=models.CharField(choices=[('has', 'دارد'), ('hasnt', 'ندارد')], max_length=15, verbose_name='پارکینگ'),
        ),
        migrations.AlterField(
            model_name='salefile',
            name='warehouse',
            field=models.CharField(choices=[('has', 'دارد'), ('hasnt', 'ندارد')], max_length=15, verbose_name='انباری'),
        ),
    ]
