# Generated by Django 5.1.7 on 2025-05-19 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0026_alter_buyer_options_alter_city_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='status',
            field=models.CharField(choices=[('acc', 'پذیرفته \u200cشده'), ('can', 'رد شده'), ('pen', 'در انتظار')], default='pen', max_length=10, verbose_name='وضعیت'),
        ),
        migrations.AddField(
            model_name='renter',
            name='status',
            field=models.CharField(choices=[('acc', 'پذیرفته \u200cشده'), ('can', 'رد شده'), ('pen', 'در انتظار')], default='pen', max_length=10, verbose_name='وضعیت'),
        ),
    ]
