# Generated by Django 5.1.7 on 2025-05-25 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0028_remove_session_visit_remove_trade_buyer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='type',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='نوع معامله'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='type',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='نوع معامله'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='type',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='نوع معامله'),
        ),
    ]
