# Generated by Django 5.1.7 on 2025-05-27 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0029_alter_session_type_alter_trade_type_alter_visit_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='type',
            field=models.CharField(blank=True, choices=[('sale', 'فروش'), ('rent', 'اجاره')], max_length=10, null=True, verbose_name='نوع معامله'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='buyer_code',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Buyer Code'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='rent_file_code',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Rent File Code'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='renter_code',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Renter Code'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='sale_file_code',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Sale File Code'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='type',
            field=models.CharField(blank=True, choices=[('sale', 'فروش'), ('rent', 'اجاره')], max_length=10, null=True, verbose_name='نوع معامله'),
        ),
    ]
