# Generated by Django 5.1.7 on 2025-05-28 13:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0030_alter_session_type_alter_visit_buyer_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits', to=settings.AUTH_USER_MODEL, verbose_name='مشاور'),
        ),
    ]
