# Generated by Django 5.1.7 on 2025-05-29 09:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0031_visit_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to=settings.AUTH_USER_MODEL, verbose_name='مشاور'),
        ),
        migrations.AlterField(
            model_name='session',
            name='buyer_code',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Buyer Code'),
        ),
        migrations.AlterField(
            model_name='session',
            name='rent_file_code',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Rent File Code'),
        ),
        migrations.AlterField(
            model_name='session',
            name='renter_code',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Renter Code'),
        ),
        migrations.AlterField(
            model_name='session',
            name='sale_file_code',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Sale File Code'),
        ),
        migrations.AlterField(
            model_name='session',
            name='status',
            field=models.CharField(choices=[('sub', 'ثبت شده'), ('end', 'خاتمه یافته')], default='sub', max_length=10, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='session',
            name='visit_code',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Visit Code'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='status',
            field=models.CharField(choices=[('sub', 'ثبت شده'), ('end', 'خاتمه یافته')], default='sub', max_length=10, verbose_name='وضعیت'),
        ),
    ]
