# Generated by Django 5.1.7 on 2025-05-29 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0032_session_agent_alter_session_buyer_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='visit_code',
        ),
    ]
