# Generated by Django 5.1.7 on 2025-05-29 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0033_remove_session_visit_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='followup_code_status',
            field=models.CharField(choices=[('tkn', 'گرفته شده'), ('ntk', 'گرفته نشده')], default='ntk', max_length=10, verbose_name='Follow-up Code Status'),
        ),
    ]
