# Generated by Django 5.1.7 on 2025-05-29 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0034_trade_followup_code_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='type',
            field=models.CharField(blank=True, choices=[('sale', 'فروش'), ('rent', 'اجاره')], max_length=10, null=True, verbose_name='نوع معامله'),
        ),
    ]
