# Generated by Django 5.1.7 on 2025-05-30 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0036_trade_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='contract_buyer',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Contract Customer (Buyer)'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='contract_owner',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Contract Owner (Seller / Lessor)'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='contract_renter',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Contract Customer (Renter)'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='followup_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='کد پیگیری'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='followup_code_status',
            field=models.CharField(choices=[('tkn', 'گرفته شده'), ('ntk', 'گرفته نشده')], default='ntk', max_length=10, verbose_name='Followup Code Status'),
        ),
    ]
