# Generated by Django 5.1.7 on 2025-05-30 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0037_alter_trade_contract_buyer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskBoss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, choices=[('sf', 'فایل فروش'), ('rf', 'فایل اجاره'), ('by', 'خریدار'), ('rt', 'مستاجر'), ('ps', 'آگهی\u200cدهنده'), ('ts', 'وظیفه')], max_length=10, null=True, verbose_name='نوع')),
                ('condition', models.CharField(blank=True, choices=[('op', 'باز'), ('cl', 'بسته')], max_length=10, null=True, verbose_name='وضعیت وظیفه مدیر')),
                ('code', models.CharField(blank=True, max_length=6, null=True, unique=True)),
                ('datetime_created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ و زمان ایجاد')),
                ('new_buyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='new_buyers', to='dashboard.buyer', verbose_name='خریدار جدید')),
                ('new_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='new_persons', to='dashboard.person', verbose_name='آگهی\u200cدهنده جدید')),
                ('new_rent_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='new_rent_files', to='dashboard.rentfile', verbose_name='فایل اجاره جدید')),
                ('new_renter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='new_renter', to='dashboard.renter', verbose_name='مستاجر جدید')),
                ('new_sale_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='new_sale_files', to='dashboard.salefile', verbose_name='فایل فروش جدید')),
                ('new_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='new_tasks', to='dashboard.person', verbose_name='وظیفه جدید')),
            ],
            options={
                'ordering': ('-datetime_created',),
            },
        ),
    ]
