# Generated by Django 5.1.7 on 2025-05-31 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0038_taskboss'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskboss',
            options={'ordering': ('-datetime_created',), 'verbose_name': 'وظیفه مدیریتی', 'verbose_name_plural': 'وظایف مدیریتی'},
        ),
        migrations.AlterField(
            model_name='taskboss',
            name='code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
