# Generated by Django 5.1.7 on 2025-05-31 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0039_alter_taskboss_options_alter_taskboss_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='کد'),
        ),
        migrations.AlterField(
            model_name='renter',
            name='code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='کد'),
        ),
        migrations.AlterField(
            model_name='session',
            name='code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='کد'),
        ),
        migrations.AlterField(
            model_name='task',
            name='code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='taskboss',
            name='condition',
            field=models.CharField(blank=True, choices=[('op', 'باز'), ('cl', 'بسته')], default='cl', max_length=10, null=True, verbose_name='وضعیت وظیفه مدیر'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='کد'),
        ),
    ]
