# Generated by Django 5.1.7 on 2025-05-31 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0040_alter_buyer_code_alter_renter_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskboss',
            name='new_task',
        ),
        migrations.AddField(
            model_name='taskboss',
            name='ur_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ur_tasks', to='dashboard.task', verbose_name='وظیفه تحویل داده شده'),
        ),
    ]
