# Generated by Django 5.1.7 on 2025-05-31 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0041_remove_taskboss_new_task_taskboss_ur_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskboss',
            name='condition',
            field=models.CharField(blank=True, choices=[('op', 'باز'), ('cl', 'بسته')], default='op', max_length=10, null=True, verbose_name='وضعیت وظیفه مدیر'),
        ),
    ]
