# Generated by Django 5.1.7 on 2025-05-31 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0042_alter_taskboss_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='datetime_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
