# Generated by Django 5.1.7 on 2025-05-31 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0043_person_datetime_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='datetime_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
