# Generated by Django 5.1.7 on 2025-06-02 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0044_alter_person_datetime_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ('-datetime_created',), 'verbose_name': 'شخص آگهی\u200cدهنده', 'verbose_name_plural': 'اشخاص آگهی\u200cدهنده'},
        ),
        migrations.AddField(
            model_name='visit',
            name='buyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits', to='dashboard.buyer', verbose_name='Visit Buyer'),
        ),
        migrations.AddField(
            model_name='visit',
            name='rent_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits', to='dashboard.rentfile', verbose_name='Visit Rent File'),
        ),
        migrations.AddField(
            model_name='visit',
            name='renter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits', to='dashboard.renter', verbose_name='Visit Renter'),
        ),
        migrations.AddField(
            model_name='visit',
            name='sale_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits', to='dashboard.salefile', verbose_name='Visit Sale File'),
        ),
    ]
