# Generated by Django 5.1.7 on 2025-06-02 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0045_alter_person_options_visit_buyer_visit_rent_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='buyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='dashboard.buyer', verbose_name='Visit Buyer'),
        ),
        migrations.AddField(
            model_name='session',
            name='rent_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='dashboard.rentfile', verbose_name='Visit Rent File'),
        ),
        migrations.AddField(
            model_name='session',
            name='renter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='dashboard.renter', verbose_name='Visit Renter'),
        ),
        migrations.AddField(
            model_name='session',
            name='sale_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='dashboard.salefile', verbose_name='Visit Sale File'),
        ),
    ]
