# Generated by Django 5.1.7 on 2025-06-02 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0046_session_buyer_session_rent_file_session_renter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='session_code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='Session Code'),
        ),
    ]
