# Generated by Django 5.1.7 on 2025-06-07 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0047_alter_trade_session_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskboss',
            name='new_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='new_sessions', to='dashboard.person', verbose_name='نشست جدید'),
        ),
        migrations.AddField(
            model_name='taskboss',
            name='new_trade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='new_trades', to='dashboard.person', verbose_name='معامله جدید'),
        ),
        migrations.AddField(
            model_name='taskboss',
            name='new_visit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='new_visits', to='dashboard.person', verbose_name='بازدید جدید'),
        ),
        migrations.AlterField(
            model_name='session',
            name='status',
            field=models.CharField(choices=[('sub', 'ثبت شده'), ('acc', 'تایید شده'), ('end', 'خاتمه یافته')], default='sub', max_length=10, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='taskboss',
            name='type',
            field=models.CharField(blank=True, choices=[('sf', 'فایل فروش'), ('rf', 'فایل اجاره'), ('by', 'خریدار'), ('rt', 'مستاجر'), ('ps', 'آگهی\u200cدهنده'), ('ts', 'وظیفه'), ('vs', 'بازدید'), ('ss', 'نشست'), ('td', 'معامله')], max_length=10, null=True, verbose_name='نوع'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='status',
            field=models.CharField(choices=[('sub', 'ثبت شده'), ('acc', 'تایید شده'), ('end', 'خاتمه یافته')], default='sub', max_length=10, verbose_name='وضعیت'),
        ),
    ]
