# Generated by Django 5.1.7 on 2025-06-07 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0048_taskboss_new_session_taskboss_new_trade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='boss_notes',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Boss Notes'),
        ),
        migrations.AddField(
            model_name='visit',
            name='boss_notes',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Boss Notes'),
        ),
        migrations.AlterField(
            model_name='taskboss',
            name='type',
            field=models.CharField(blank=True, choices=[('sf', 'فایل فروش'), ('rf', 'فایل اجاره'), ('by', 'خریدار'), ('rt', 'مستاجر'), ('ps', 'آگهی\u200cدهنده'), ('ts', 'وظیفه'), ('vs', 'بازدید'), ('ss', 'نشست')], max_length=10, null=True, verbose_name='نوع'),
        ),
    ]
