# Generated by Django 5.1.7 on 2025-06-07 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0049_session_boss_notes_visit_boss_notes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskboss',
            name='new_trade',
        ),
    ]
