# Generated by Django 5.1.7 on 2025-06-07 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0050_remove_taskboss_new_trade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='buyer_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Buyer Code'),
        ),
        migrations.AlterField(
            model_name='session',
            name='renter_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Renter Code'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='buyer_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Buyer Code'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='renter_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Renter Code'),
        ),
    ]
