# Generated by Django 5.1.7 on 2025-06-07 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0051_alter_session_buyer_code_alter_session_renter_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskboss',
            name='new_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='new_sessions', to='dashboard.session', verbose_name='نشست جدید'),
        ),
        migrations.AlterField(
            model_name='taskboss',
            name='new_visit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='new_visits', to='dashboard.visit', verbose_name='بازدید جدید'),
        ),
    ]
