# Generated by Django 5.1.7 on 2025-06-10 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0053_taskboss_result_session_taskboss_result_visit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='boss_final_comment',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Boss Final Comment'),
        ),
        migrations.AddField(
            model_name='visit',
            name='boss_final_comment',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Boss Final Comment'),
        ),
        migrations.AlterField(
            model_name='session',
            name='status',
            field=models.CharField(choices=[('sub', 'منتظر تایید'), ('acc', 'آماده انجام'), ('can', 'رد شده'), ('dne', 'انجام شده'), ('end', 'تایید نتیجه')], default='sub', max_length=10, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='taskboss',
            name='type',
            field=models.CharField(blank=True, choices=[('sf', 'فایل فروش جدید'), ('rf', 'فایل اجاره جدید'), ('by', 'خریدار جدید'), ('rt', 'مستاجر جدید'), ('ps', 'آگهی\u200cدهنده جدید'), ('vs', 'بازدید جدید'), ('ss', 'نشست جدید'), ('rv', 'نتیجه بازدید'), ('rs', 'نتیجه نشست'), ('ts', 'نتیجه وظیفه')], max_length=10, null=True, verbose_name='نوع'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='status',
            field=models.CharField(choices=[('sub', 'منتظر تایید'), ('acc', 'آماده انجام'), ('can', 'رد شده'), ('dne', 'انجام شده'), ('end', 'تایید نتیجه')], default='sub', max_length=10, verbose_name='وضعیت'),
        ),
    ]
