# Generated by Django 5.1.7 on 2025-06-14 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0054_session_boss_final_comment_visit_boss_final_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='datetime_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
