# Generated by Django 5.1.7 on 2025-06-25 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0055_alter_person_datetime_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='buyer_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Buyer Code'),
        ),
        migrations.AddField(
            model_name='task',
            name='rent_file_code',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Rent File Code'),
        ),
        migrations.AddField(
            model_name='task',
            name='renter_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Renter Code'),
        ),
        migrations.AddField(
            model_name='task',
            name='sale_file_code',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Sale File Code'),
        ),
        migrations.AlterField(
            model_name='task',
            name='buyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='dashboard.buyer', verbose_name='Task Buyer'),
        ),
        migrations.AlterField(
            model_name='task',
            name='rent_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='dashboard.rentfile', verbose_name='Task Rent File'),
        ),
        migrations.AlterField(
            model_name='task',
            name='renter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='dashboard.renter', verbose_name='Task Renter'),
        ),
        migrations.AlterField(
            model_name='task',
            name='sale_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='dashboard.salefile', verbose_name='Task Sale File'),
        ),
    ]
