# Generated by Django 5.1.7 on 2025-06-26 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0056_task_buyer_code_task_rent_file_code_task_renter_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusermodel',
            name='name_family',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='نام و نام خانوادگی'),
        ),
    ]
