# Generated by Django 5.1.7 on 2025-07-29 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0057_customusermodel_name_family'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='delete_request',
            field=models.CharField(blank=True, choices=[('Yes', 'بله'), ('No', 'خیر')], default='No', max_length=3, null=True, verbose_name='Delete Request'),
        ),
        migrations.AlterField(
            model_name='rentfile',
            name='source',
            field=models.CharField(blank=True, choices=[('DV', 'دیوار'), ('KS', 'کاشانو'), ('SK', 'اسکان'), ('OT', 'سایر'), ('PV', 'پیوند'), ('EH', 'احیایی'), ('PN', 'شخص')], max_length=15, null=True, verbose_name='منبع'),
        ),
        migrations.AlterField(
            model_name='salefile',
            name='source',
            field=models.CharField(blank=True, choices=[('DV', 'دیوار'), ('KS', 'کاشانو'), ('SK', 'اسکان'), ('OT', 'سایر'), ('PV', 'پیوند'), ('EH', 'احیایی'), ('PN', 'شخص')], max_length=15, null=True, verbose_name='منبع'),
        ),
    ]
