# Generated by Django 5.1.7 on 2025-07-29 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0058_person_delete_request_alter_rentfile_source_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemDeleteBoss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, choices=[('sf', 'فایل فروش حذفی'), ('rf', 'فایل اجاره حذفی'), ('by', 'خریدار حذفی'), ('rt', 'مستاجر حذفی'), ('ps', 'آگهی\u200cدهنده حذفی')], max_length=3, null=True, verbose_name='نوع آیتم')),
                ('status', models.CharField(blank=True, choices=[('op', 'باز'), ('cl', 'بسته')], max_length=3, null=True, verbose_name='وضعیت')),
                ('code', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('datetime_created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ و زمان ایجاد')),
                ('deleted_buyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deleted_buyers', to='dashboard.buyer', verbose_name='خریدار حذفی')),
                ('deleted_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deleted_persons', to='dashboard.person', verbose_name='آگهی\u200cدهنده حذفی')),
                ('deleted_rent_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deleted_rent_files', to='dashboard.rentfile', verbose_name='فایل اجاره حذفی')),
                ('deleted_renter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deleted_renter', to='dashboard.renter', verbose_name='مستاجر حذفی')),
                ('deleted_sale_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deleted_sale_files', to='dashboard.salefile', verbose_name='فایل فروش حذفی')),
            ],
            options={
                'verbose_name': 'آیتم حذفی',
                'verbose_name_plural': 'آیتم\u200cهای حذفی',
                'ordering': ('-datetime_created',),
            },
        ),
    ]
