# Generated by Django 5.1.7 on 2025-07-29 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0059_itemdeleteboss'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='delete_request',
            field=models.CharField(blank=True, choices=[('Yes', 'بله'), ('No', 'خیر')], default='No', max_length=3, null=True, verbose_name='Delete Request'),
        ),
        migrations.AddField(
            model_name='renter',
            name='delete_request',
            field=models.CharField(blank=True, choices=[('Yes', 'بله'), ('No', 'خیر')], default='No', max_length=3, null=True, verbose_name='Delete Request'),
        ),
        migrations.AddField(
            model_name='rentfile',
            name='delete_request',
            field=models.CharField(blank=True, choices=[('Yes', 'بله'), ('No', 'خیر')], default='No', max_length=3, null=True, verbose_name='Delete Request'),
        ),
        migrations.AddField(
            model_name='salefile',
            name='delete_request',
            field=models.CharField(blank=True, choices=[('Yes', 'بله'), ('No', 'خیر')], default='No', max_length=3, null=True, verbose_name='Delete Request'),
        ),
        migrations.DeleteModel(
            name='ItemDeleteBoss',
        ),
    ]
