# Generated by Django 5.1.7 on 2025-09-03 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0060_buyer_delete_request_renter_delete_request_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='phone_number',
            field=models.CharField(max_length=11, verbose_name='تلفن همراه'),
        ),
        migrations.AlterField(
            model_name='renter',
            name='phone_number',
            field=models.CharField(max_length=11, verbose_name='تلفن همراه'),
        ),
    ]
