# Generated by Django 5.1.7 on 2025-09-03 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0061_alter_buyer_phone_number_alter_renter_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='phone_number',
            field=models.CharField(max_length=11, verbose_name='تلفن همراه'),
        ),
    ]
