# Generated by Django 5.1.7 on 2025-09-07 13:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0064_buyer_created_by_renter_created_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('sf', 'فایل فروش'), ('rf', 'فایل اجاره'), ('by', 'خریدار'), ('rt', 'مستاجر')], max_length=10, verbose_name='نوع نشان\u200cشده')),
                ('code', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=150, unique=True, verbose_name='اسلاگ')),
                ('datetime_created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ و زمان ایجاد')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to=settings.AUTH_USER_MODEL, verbose_name='مشاور')),
                ('buyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='dashboard.buyer', verbose_name='خریدار نشان\u200cشده')),
                ('rent_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='dashboard.rentfile', verbose_name='فایل اجاره نشان\u200cشده')),
                ('renter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='dashboard.renter', verbose_name='مستاجر نشان\u200cشده')),
                ('sale_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='dashboard.salefile', verbose_name='فایل فروش نشان\u200cشده')),
            ],
            options={
                'verbose_name': 'نشان\u200cشده',
                'verbose_name_plural': 'نشان\u200cشده\u200cها',
                'ordering': ('-datetime_created',),
            },
        ),
    ]
