# Generated by Django 5.1.7 on 2025-09-07 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0065_mark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mark',
            name='code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='mark',
            name='slug',
            field=models.SlugField(blank=True, max_length=150, verbose_name='اسلاگ'),
        ),
    ]
