# Generated by Django 5.1.7 on 2025-09-17 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0066_alter_mark_code_alter_mark_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='contract_buyer',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='نام خریدار (قرارداد)'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='contract_owner',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='نام فروشنده / موجر (قرارداد)'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='contract_renter',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='نام مستاجر (قرارداد)'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='followup_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='کد رهگیری'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='followup_code_status',
            field=models.CharField(choices=[('tkn', 'گرفته شده'), ('ntk', 'گرفته نشده')], default='ntk', max_length=10, verbose_name='وضعیت کد رهگیری'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trades', to='dashboard.session', verbose_name='جلسه'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='session_code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='کد جلسه'),
        ),
    ]
