# Generated by Django 5.1.7 on 2025-09-20 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0067_alter_trade_contract_buyer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salefile',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='files/pdfs/', verbose_name='گالری فایل'),
        ),
    ]
