# Generated by Django 5.1.7 on 2025-09-21 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0068_salefile_pdf_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salefile',
            name='pdf_file',
        ),
    ]
