# Generated by Django 5.1.7 on 2025-09-30 10:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0069_remove_salefile_pdf_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentfile',
            name='street',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='خیابان اصلی'),
        ),
        migrations.AddField(
            model_name='salefile',
            name='street',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='خیابان اصلی'),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buyers', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد شده توسط'),
        ),
        migrations.AlterField(
            model_name='renter',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='renters', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد شده توسط'),
        ),
        migrations.AlterField(
            model_name='rentfile',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rent_files', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد شده توسط'),
        ),
        migrations.AlterField(
            model_name='salefile',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_files', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد شده توسط'),
        ),
    ]
