# Generated by Django 5.1.7 on 2025-10-02 12:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0070_rentfile_street_salefile_street_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount', models.TextField(blank=True, max_length=500, null=True, verbose_name='تخفیف')),
                ('service', models.TextField(blank=True, max_length=500, null=True, verbose_name='سرویس')),
                ('evaluation', models.TextField(blank=True, max_length=500, null=True, verbose_name='کارشناسی')),
                ('ads', models.TextField(blank=True, max_length=500, null=True, verbose_name='آگهی')),
                ('description', models.TextField(blank=True, max_length=1000, null=True, verbose_name='توضیحات')),
                ('boss_note', models.TextField(blank=True, max_length=1000, null=True, verbose_name='توضیحات مدیر')),
                ('status', models.CharField(choices=[('wfb', 'منتظر نظر مدیر'), ('wfa', 'منتظر مشاهده نظر مدیر'), ('cls', 'بسته')], default='wfb', max_length=10, verbose_name='وضعیت')),
                ('date', models.CharField(max_length=200, verbose_name='تاریخ')),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to=settings.AUTH_USER_MODEL, verbose_name='مشاور')),
            ],
            options={
                'verbose_name': 'گزارش روزانه',
                'verbose_name_plural': 'گزارش\u200cهای روزانه',
                'ordering': ['-date'],
            },
        ),
    ]
