# Generated by Django 5.1.7 on 2025-10-02 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0071_dailyreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyreport',
            name='url_identifier',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
