# Generated by Django 5.1.7 on 2025-10-02 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0072_dailyreport_url_identifier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyreport',
            name='url_identifier',
        ),
    ]
