# Generated by Django 5.1.7 on 2025-10-04 15:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0073_remove_dailyreport_url_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyreport',
            name='status',
            field=models.CharField(choices=[('wfb', 'منتظر ثبت نظر مدیر'), ('wfr', 'منتظر مشاهده نظر مدیر'), ('cls', 'بسته')], default='wfb', max_length=10, verbose_name='وضعیت'),
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, max_length=1000, null=True, verbose_name='توضیحات')),
                ('boss_note', models.TextField(blank=True, max_length=1000, null=True, verbose_name='توضیحات مدیر')),
                ('status', models.CharField(choices=[('wfb', 'منتظر ثبت نظر مدیر'), ('wfr', 'منتظر مشاهده نظر مدیر'), ('cls', 'بسته')], default='wfb', max_length=10, verbose_name='وضعیت')),
                ('date', models.CharField(max_length=200, verbose_name='تاریخ')),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='new_reports', to=settings.AUTH_USER_MODEL, verbose_name='مشاور')),
            ],
            options={
                'verbose_name': 'گزارش روزانه',
                'verbose_name_plural': 'گزارش\u200cهای روزانه',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ReportItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='کد فایل')),
                ('customer_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='کد مشتری')),
                ('description', models.TextField(blank=True, max_length=1000, null=True, verbose_name='توضیحات')),
                ('type', models.CharField(choices=[('ads', 'آگهی'), ('eva', 'کارشناسی'), ('dis', 'تخفیف'), ('ser', 'سرویس')], max_length=10, verbose_name='نوع')),
                ('datetime_created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ و زمان ایجاد')),
                ('report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ads', to='dashboard.report', verbose_name='کزارش')),
            ],
            options={
                'verbose_name': 'آگهی',
                'verbose_name_plural': 'آگهی\u200cها',
                'ordering': ['-datetime_created'],
            },
        ),
    ]
