# Generated by Django 5.1.7 on 2025-10-05 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0074_alter_dailyreport_status_report_reportitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ['-date'], 'verbose_name': 'گزارش', 'verbose_name_plural': 'گزارش\u200cها'},
        ),
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('wfb', 'منتظر نظر مدیر'), ('wfr', 'منتظر مشاهده نظر مدیر'), ('cls', 'بسته')], default='wfb', max_length=10, verbose_name='وضعیت'),
        ),
        migrations.DeleteModel(
            name='DailyReport',
        ),
    ]
