# Generated by Django 5.1.7 on 2025-10-07 14:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('dashboard', '0075_alter_report_options_alter_report_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('announcement_type', models.CharField(choices=[('sf', 'فایل فروش'), ('rf', 'فایل اجاره'), ('by', 'خریدار'), ('rt', 'مستاجر')], max_length=20, verbose_name='نوع')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال بودن')),
                ('datetime_created', models.DateTimeField(auto_now_add=True, verbose_name='زمان ساخت')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_announcements', to=settings.AUTH_USER_MODEL, verbose_name='منشا')),
                ('viewed_by', models.ManyToManyField(blank=True, related_name='viewed_announcements', to=settings.AUTH_USER_MODEL, verbose_name='بیننده')),
                ('visible_to', models.ManyToManyField(blank=True, related_name='visible_announcements', to=settings.AUTH_USER_MODEL, verbose_name='مخاطب')),
            ],
            options={
                'verbose_name': 'اعلان',
                'verbose_name_plural': 'اعلان\u200cها',
                'ordering': ['-datetime_created'],
            },
        ),
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_type', models.CharField(choices=[('buyers_to_sale_file', 'خریداران برای فایل فروش'), ('sale_files_to_buyer', 'فایل\u200cهای فروش برای خریداران'), ('renters_to_rent_file', 'مستاجران برای فایل اجاره'), ('rent_files_to_renter', 'فایل\u200cهای اجاره برای مستاجران')], max_length=20, verbose_name='نوع')),
                ('message', models.TextField(blank=True, max_length=1000, null=True, verbose_name='پبغام')),
                ('status', models.CharField(choices=[('sent', 'ارسال\u200cشده'), ('viewed', 'دیده\u200cشده'), ('responded', 'پاسخ داده\u200cشده'), ('closed', 'بسته')], default='sent', max_length=20, verbose_name='وضعیت')),
                ('datetime_viewed', models.DateTimeField(blank=True, null=True, verbose_name='زمان مشاهده')),
                ('datetime_created', models.DateTimeField(auto_now_add=True, verbose_name='زمان ساخت')),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='dashboard.announcement', verbose_name='اعلان')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_interactions', to=settings.AUTH_USER_MODEL, verbose_name='گیرنده')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_interactions', to=settings.AUTH_USER_MODEL, verbose_name='فرستنده')),
            ],
            options={
                'verbose_name': 'تعامل',
                'verbose_name_plural': 'تعامل\u200cها',
                'ordering': ['-datetime_created'],
            },
        ),
        migrations.CreateModel(
            name='InteractionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('cached_price', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='قیمت کش')),
                ('cached_area', models.PositiveIntegerField(blank=True, null=True, verbose_name='متراژ کش')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='یادداشت')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('interaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='dashboard.interaction', verbose_name='تعامل')),
            ],
            options={
                'verbose_name': 'آیتم تعامل',
                'verbose_name_plural': 'آیتم\u200cهای تعامل',
            },
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['content_type', 'object_id'], name='dashboard_a_content_c4abe0_idx'),
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['-datetime_created'], name='dashboard_a_datetim_db0b82_idx'),
        ),
        migrations.AddIndex(
            model_name='interaction',
            index=models.Index(fields=['sender', '-datetime_created'], name='dashboard_i_sender__c46d36_idx'),
        ),
        migrations.AddIndex(
            model_name='interaction',
            index=models.Index(fields=['receiver', '-datetime_created'], name='dashboard_i_receive_6d54cc_idx'),
        ),
        migrations.AddIndex(
            model_name='interaction',
            index=models.Index(fields=['status'], name='dashboard_i_status_9d76b1_idx'),
        ),
        migrations.AddIndex(
            model_name='interactionitem',
            index=models.Index(fields=['content_type', 'object_id'], name='dashboard_i_content_ec816d_idx'),
        ),
    ]
