# Generated by Django 5.1.7 on 2025-10-13 18:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0076_announcement_interaction_interactionitem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interaction',
            name='interaction_type',
            field=models.CharField(choices=[('buyers_to_sale_file', 'خریداران برای فایل فروش'), ('renters_to_rent_file', 'مستاجران برای فایل اجاره'), ('sale_files_to_buyer', 'فایل\u200cهای فروش برای خریداران'), ('rent_files_to_renter', 'فایل\u200cهای اجاره برای مستاجران')], max_length=20, verbose_name='نوع'),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='status',
            field=models.CharField(choices=[('sent', 'ارسال\u200cشده'), ('received', 'دیده\u200cشده')], default='sent', max_length=20, verbose_name='وضعیت'),
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('date', models.CharField(max_length=200, verbose_name='مهلت انجام')),
                ('sale_file_code', models.CharField(blank=True, max_length=6, null=True, verbose_name='Sale File Code')),
                ('rent_file_code', models.CharField(blank=True, max_length=6, null=True, verbose_name='Rent File Code')),
                ('buyer_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='Buyer Code')),
                ('renter_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='Renter Code')),
                ('code', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('description', models.TextField(blank=True, max_length=1000, null=True, verbose_name='توضیحات')),
                ('status', models.CharField(choices=[('OP', 'باز'), ('UR', 'تحویل داده شده'), ('CL', 'بسته')], default='OP', max_length=10, verbose_name='وضعیت')),
                ('datetime_created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ و زمان ایجاد')),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reminders', to=settings.AUTH_USER_MODEL, verbose_name='مشاور')),
                ('buyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reminders', to='dashboard.buyer', verbose_name='خریدار')),
                ('rent_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reminders', to='dashboard.rentfile', verbose_name='فایل اجاره')),
                ('renter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reminders', to='dashboard.renter', verbose_name='مستاجر')),
                ('sale_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reminders', to='dashboard.salefile', verbose_name='فایل فروش')),
            ],
            options={
                'verbose_name': 'یادآور',
                'verbose_name_plural': 'یادآورها',
                'ordering': ('-datetime_created',),
            },
        ),
    ]
