# Generated by Django 5.1.7 on 2025-10-15 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0077_alter_interaction_interaction_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskboss',
            name='ur_task',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='agent',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='buyer',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='rent_file',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='renter',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='sale_file',
        ),
        migrations.RemoveField(
            model_name='taskboss',
            name='result_visit',
        ),
        migrations.RemoveField(
            model_name='taskboss',
            name='new_visit',
        ),
        migrations.AlterField(
            model_name='taskboss',
            name='type',
            field=models.CharField(blank=True, choices=[('sf', 'فایل فروش جدید'), ('rf', 'فایل اجاره جدید'), ('by', 'خریدار جدید'), ('rt', 'مستاجر جدید'), ('ps', 'آگهی\u200cدهنده جدید'), ('ss', 'نشست جدید'), ('rs', 'نتیجه نشست')], max_length=10, null=True, verbose_name='نوع'),
        ),
        migrations.DeleteModel(
            name='Task',
        ),
        migrations.DeleteModel(
            name='Visit',
        ),
    ]
