# Generated by Django 5.1.7 on 2025-10-26 13:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('dashboard', '0078_remove_taskboss_ur_task_remove_visit_agent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotifiedTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(help_text='Format: 1404/07/12', max_length=10, verbose_name='تاریخ')),
                ('task_type', models.CharField(choices=[('similar_file', 'یک فایل برای پیشنهاد دارید'), ('similar_customer', 'یک مشتری برای پیشنهاد دارید'), ('discount_task', 'اخذ تخفیف روزانه'), ('service_task', 'سرویس (بازدید) روزانه'), ('ads_task', 'درج آگهی روزانه'), ('evaluation_task', 'کارشناسی روزانه'), ('daily_report', 'نوشتن گزارش روزانه'), ('reminder', 'امروز یک یادآوری دارید')], max_length=20, verbose_name='نوع وظیفه')),
                ('status', models.CharField(choices=[('waiting', 'در انتظار'), ('done_on_time', 'به موقع انجام شده'), ('done_late', 'با تاخیر انجام شده'), ('delayed', 'تعویق یافته')], default='waiting', max_length=20, verbose_name='وضعیت')),
                ('result', models.TextField(blank=True, null=True, verbose_name='نتیجه')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان و تاریخ ایجاد')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان و تاریخ تکمیل')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notified_tasks', to=settings.AUTH_USER_MODEL, verbose_name='مشاور')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('related_announcement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_tasks', to='dashboard.announcement', verbose_name='اعلان مربوطه')),
                ('related_reminder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notified_tasks', to='dashboard.reminder', verbose_name='یادآور مربوطه')),
                ('target_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='targeted_tasks', to=settings.AUTH_USER_MODEL, verbose_name='مشاور هدف')),
            ],
            options={
                'verbose_name': 'وظیفه روزانه',
                'verbose_name_plural': 'وظایف روزانه',
                'ordering': ['-date', 'status', 'task_type'],
                'indexes': [models.Index(fields=['agent', 'date'], name='dashboard_n_agent_i_5268ca_idx'), models.Index(fields=['date', 'status'], name='dashboard_n_date_586943_idx'), models.Index(fields=['task_type', 'status'], name='dashboard_n_task_ty_5192aa_idx')],
                'unique_together': {('agent', 'date', 'task_type', 'content_type', 'object_id')},
            },
        ),
        migrations.CreateModel(
            name='NotifiedTaskStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_tasks', models.PositiveIntegerField(default=0, verbose_name='تمام وظایف')),
                ('done_on_time', models.PositiveIntegerField(default=0, verbose_name='وظایف به موقع انجام شده')),
                ('done_late', models.PositiveIntegerField(default=0, verbose_name='وظایف با تاخیر انجام شده')),
                ('delayed', models.PositiveIntegerField(default=0, verbose_name='وظایف تعویق یافته')),
                ('waiting', models.PositiveIntegerField(default=0, verbose_name='وظایف در انتظار')),
                ('similar_file_count', models.PositiveIntegerField(default=0)),
                ('similar_customer_count', models.PositiveIntegerField(default=0)),
                ('discount_task_count', models.PositiveIntegerField(default=0)),
                ('service_task_count', models.PositiveIntegerField(default=0)),
                ('ads_task_count', models.PositiveIntegerField(default=0)),
                ('evaluation_task_count', models.PositiveIntegerField(default=0)),
                ('daily_report_count', models.PositiveIntegerField(default=0)),
                ('reminder_count', models.PositiveIntegerField(default=0)),
                ('completion_rate', models.FloatField(default=0.0, verbose_name='نرخ تکمیل')),
                ('on_time_rate', models.FloatField(default=0.0, verbose_name='نرخ تکمیل به موقع')),
                ('period_type', models.CharField(choices=[('daily', 'روزانه'), ('weekly', 'هفتگی'), ('monthly', 'ماهانه')], max_length=10, verbose_name='دوره زمانی')),
                ('period_start', models.CharField(max_length=10, verbose_name='آغاز دوره زمانی')),
                ('period_end', models.CharField(max_length=10, verbose_name='پایان دوره زمانی')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_statistics', to=settings.AUTH_USER_MODEL, verbose_name='مشاور')),
            ],
            options={
                'verbose_name': 'آمار وظایف',
                'verbose_name_plural': 'آمارهای وظایف',
                'ordering': ['-period_start', 'agent'],
                'indexes': [models.Index(fields=['agent', 'period_type', 'period_start'], name='dashboard_n_agent_i_cbe51d_idx')],
                'unique_together': {('agent', 'period_type', 'period_start', 'period_end')},
            },
        ),
    ]
