# Generated by Django 5.1.7 on 2025-10-26 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0079_notifiedtask_notifiedtaskstats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifiedtask',
            name='date',
            field=models.CharField(max_length=50, verbose_name='تاریخ'),
        ),
    ]
