# Generated by Django 5.1.7 on 2025-10-29 18:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('dashboard', '0080_alter_notifiedtask_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyTaskStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=10, verbose_name='تاریخ')),
                ('report_done', models.BooleanField(default=False, verbose_name='گزارش ثبت شده')),
                ('ads_done', models.BooleanField(default=False, verbose_name='انجام وظیفه آگهی')),
                ('eva_done', models.BooleanField(default=False, verbose_name='انجام وظیفه کارشناسی')),
                ('dis_done', models.BooleanField(default=False, verbose_name='انجام وظیفه تخفیف')),
                ('ser_done', models.BooleanField(default=False, verbose_name='انجام وظیفه سرویس')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Daily Task Status',
                'verbose_name_plural': 'Daily Task Statuses',
                'ordering': ['-date'],
            },
        ),
        migrations.AlterModelOptions(
            name='notifiedtask',
            options={'ordering': ['-created_at', 'status'], 'verbose_name': 'Notified Task', 'verbose_name_plural': 'Notified Tasks'},
        ),
        migrations.AlterModelOptions(
            name='notifiedtaskstats',
            options={'ordering': ['-period_start', 'agent'], 'verbose_name': 'Task Statistics', 'verbose_name_plural': 'Task Statistics'},
        ),
        migrations.RemoveIndex(
            model_name='notifiedtask',
            name='dashboard_n_agent_i_5268ca_idx',
        ),
        migrations.RemoveIndex(
            model_name='notifiedtask',
            name='dashboard_n_date_586943_idx',
        ),
        migrations.AlterUniqueTogether(
            name='notifiedtask',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='notifiedtaskstats',
            name='ads_task_count',
        ),
        migrations.RemoveField(
            model_name='notifiedtaskstats',
            name='completion_rate',
        ),
        migrations.RemoveField(
            model_name='notifiedtaskstats',
            name='daily_report_count',
        ),
        migrations.RemoveField(
            model_name='notifiedtaskstats',
            name='delayed',
        ),
        migrations.RemoveField(
            model_name='notifiedtaskstats',
            name='discount_task_count',
        ),
        migrations.RemoveField(
            model_name='notifiedtaskstats',
            name='done_late',
        ),
        migrations.RemoveField(
            model_name='notifiedtaskstats',
            name='done_on_time',
        ),
        migrations.RemoveField(
            model_name='notifiedtaskstats',
            name='evaluation_task_count',
        ),
        migrations.RemoveField(
            model_name='notifiedtaskstats',
            name='on_time_rate',
        ),
        migrations.RemoveField(
            model_name='notifiedtaskstats',
            name='reminder_count',
        ),
        migrations.RemoveField(
            model_name='notifiedtaskstats',
            name='service_task_count',
        ),
        migrations.RemoveField(
            model_name='notifiedtaskstats',
            name='similar_customer_count',
        ),
        migrations.RemoveField(
            model_name='notifiedtaskstats',
            name='similar_file_count',
        ),
        migrations.RemoveField(
            model_name='notifiedtaskstats',
            name='total_tasks',
        ),
        migrations.RemoveField(
            model_name='notifiedtaskstats',
            name='waiting',
        ),
        migrations.AddField(
            model_name='notifiedtask',
            name='related_interaction_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notified_tasks', to='dashboard.interaction', verbose_name='آیتم تعاملی مربوطه'),
        ),
        migrations.AddField(
            model_name='notifiedtaskstats',
            name='announcement_suggestions_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='notifiedtaskstats',
            name='completed_ads',
            field=models.PositiveIntegerField(default=0, verbose_name='آگهی\u200cهای منتشر شده'),
        ),
        migrations.AddField(
            model_name='notifiedtaskstats',
            name='completed_dis',
            field=models.PositiveIntegerField(default=0, verbose_name='تخفیف\u200cهای اخذ شده'),
        ),
        migrations.AddField(
            model_name='notifiedtaskstats',
            name='completed_eva',
            field=models.PositiveIntegerField(default=0, verbose_name='کارشناسی\u200cهای انجام شده'),
        ),
        migrations.AddField(
            model_name='notifiedtaskstats',
            name='completed_reports',
            field=models.PositiveIntegerField(default=0, verbose_name='گزارش\u200cهای ثبت شده'),
        ),
        migrations.AddField(
            model_name='notifiedtaskstats',
            name='completed_ser',
            field=models.PositiveIntegerField(default=0, verbose_name='سرویس\u200cهای انجام شده'),
        ),
        migrations.AddField(
            model_name='notifiedtaskstats',
            name='daily_task_completion_rate',
            field=models.FloatField(default=0.0, verbose_name='نرخ انجام وظایف روزانه'),
        ),
        migrations.AddField(
            model_name='notifiedtaskstats',
            name='done_notified_tasks',
            field=models.PositiveIntegerField(default=0, verbose_name='وظایف انجام شده'),
        ),
        migrations.AddField(
            model_name='notifiedtaskstats',
            name='notified_task_completion_rate',
            field=models.FloatField(default=0.0, verbose_name='نرخ انجام وظایف'),
        ),
        migrations.AddField(
            model_name='notifiedtaskstats',
            name='overall_completion_rate',
            field=models.FloatField(default=0.0, verbose_name='نرخ کل'),
        ),
        migrations.AddField(
            model_name='notifiedtaskstats',
            name='received_interaction_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='notifiedtaskstats',
            name='total_daily_task_days',
            field=models.PositiveIntegerField(default=0, verbose_name='تمام روزها'),
        ),
        migrations.AddField(
            model_name='notifiedtaskstats',
            name='total_notified_tasks',
            field=models.PositiveIntegerField(default=0, verbose_name='تمام وظایف'),
        ),
        migrations.AddField(
            model_name='notifiedtaskstats',
            name='waiting_notified_tasks',
            field=models.PositiveIntegerField(default=0, verbose_name='تمام در انتظار'),
        ),
        migrations.AlterField(
            model_name='notifiedtask',
            name='related_announcement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suggestion_tasks', to='dashboard.announcement', verbose_name='اعلان مربوطه'),
        ),
        migrations.AlterField(
            model_name='notifiedtask',
            name='status',
            field=models.CharField(choices=[('waiting', 'در انتظار'), ('done', 'انجام شده')], default='waiting', max_length=20, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='notifiedtask',
            name='task_type',
            field=models.CharField(choices=[('announcement_suggestions', 'پیشنهادات برای اعلان'), ('received_interaction', 'تعامل دریافتی')], max_length=30, verbose_name='نوع وظیفه'),
        ),
        migrations.AlterField(
            model_name='notifiedtaskstats',
            name='period_type',
            field=models.CharField(choices=[('daily', 'روزانه'), ('weekly', 'هفتگی'), ('monthly', 'ماهانه')], max_length=10, verbose_name='نوع دوره زمانی'),
        ),
        migrations.AddIndex(
            model_name='notifiedtask',
            index=models.Index(fields=['agent', 'status'], name='dashboard_n_agent_i_d3d4df_idx'),
        ),
        migrations.AddField(
            model_name='dailytaskstatus',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_task_statuses', to=settings.AUTH_USER_MODEL, verbose_name='مشاور'),
        ),
        migrations.AddField(
            model_name='dailytaskstatus',
            name='report',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_task_status', to='dashboard.report', verbose_name='گزارش'),
        ),
        migrations.RemoveField(
            model_name='notifiedtask',
            name='date',
        ),
        migrations.RemoveField(
            model_name='notifiedtask',
            name='related_reminder',
        ),
        migrations.RemoveField(
            model_name='notifiedtask',
            name='target_agent',
        ),
        migrations.AddIndex(
            model_name='dailytaskstatus',
            index=models.Index(fields=['agent', 'date'], name='dashboard_d_agent_i_773df6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dailytaskstatus',
            unique_together={('agent', 'date')},
        ),
    ]
