# Generated by Django 5.1.7 on 2025-10-29 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0081_dailytaskstatus_alter_notifiedtask_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifiedtask',
            name='date',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='تاریخ'),
        ),
    ]
