# Generated by Django 5.1.7 on 2025-11-02 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0082_notifiedtask_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailytaskstatus',
            options={'ordering': ['-date'], 'verbose_name': 'وظایف (وضعیت)', 'verbose_name_plural': 'وظایف (وضعیت)'},
        ),
        migrations.AlterModelOptions(
            name='notifiedtask',
            options={'ordering': ['-created_at', 'status'], 'verbose_name': 'وظیفه', 'verbose_name_plural': 'وظایف'},
        ),
        migrations.AlterModelOptions(
            name='notifiedtaskstats',
            options={'ordering': ['-period_start', 'agent'], 'verbose_name': 'وظایف (آمار)', 'verbose_name_plural': 'وظایف (آمار)'},
        ),
        migrations.AlterField(
            model_name='notifiedtask',
            name='related_interaction_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notified_tasks', to='dashboard.interactionitem', verbose_name='آیتم تعاملی مربوطه'),
        ),
        migrations.AlterField(
            model_name='notifiedtask',
            name='task_type',
            field=models.CharField(choices=[('announcement_suggestions', 'پیشنهاداتی که باید ارسال کنید'), ('received_interaction', 'پیشنهاداتی که دریافت کردید')], max_length=30, verbose_name='نوع وظیفه'),
        ),
        migrations.AlterField(
            model_name='reportitem',
            name='report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='dashboard.report', verbose_name='کزارش'),
        ),
    ]
