# Generated by Django 5.1.7 on 2025-11-07 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('dashboard', '0083_alter_dailytaskstatus_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='notifiedtaskstats',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='notifiedtaskstats',
            name='agent',
        ),
        migrations.AlterField(
            model_name='customusermodel',
            name='title',
            field=models.CharField(blank=True, choices=[('bs', 'مدیر'), ('fp', 'مشاور فایل\u200cها'), ('cp', 'مشاور مشتریان'), ('bt', 'مشاور دوگانه'), ('nd', 'همه محلات')], max_length=10, null=True, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='status',
            field=models.CharField(choices=[('unseen', 'مشاهده\u200cنشده'), ('seen', 'مشاهده\u200cشده')], default='unseen', max_length=20, verbose_name='وضعیت'),
        ),
        migrations.AddIndex(
            model_name='interactionitem',
            index=models.Index(fields=['interaction', 'content_type'], name='dashboard_i_interac_78db6b_idx'),
        ),
        migrations.DeleteModel(
            name='NotifiedTaskStats',
        ),
    ]
